V ALLIANCE : 4
H pvsse_sp,L,23/ 2/95
C ck,UNKNOWN,EXTERNAL,1
C vdde,UNKNOWN,EXTERNAL,2
C vddi,UNKNOWN,EXTERNAL,3
C vsse,UNKNOWN,EXTERNAL,4
C vssi,UNKNOWN,EXTERNAL,5
S 5,EXTERNAL,0,vssi
S 4,EXTERNAL,0,vsse
S 3,EXTERNAL,0,vddi
S 2,EXTERNAL,0,vdde
S 1,EXTERNAL,0,ck
EOF
