.\"   $Id: addbddvarbefore.3,v 1.1.1.1 2002/03/18 11:26:50 ludo Exp $
.\" @(#)addbddvarbefore.2 2.7 96/07/02 ; Labo masi cao-vlsi; Author : Jacomme Ludovic
.TH ADDBDDVARBEFORE 3 "October 1, 1997" "ASIM/LIP6" "BDD FUNCTIONS"
.SH NAME
addbddvarbefore \- adds a new variable, before an existing one.
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "bdd101.h"
bddnode \(**addbddvarbefore( BddSystem )
  bddsystem \(**BddSystem;
  bddindex      Index;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIBddSystem\fP
The \fBbdd\fP system.
.TP
\fIIndex\fP
The \fBbdd\fP index of an existing variable.
.SH DESCRIPTION
\fBaddbddvarbefore\fP creates a new variable, with the number
\fIBddSystem\fP->INDEX_TO_VAR[ \fIIndex\fP ]
in the \fBbdd\fP system \fIBddSystem\fP.
If a null pointer is given, the default \fBbdd\fP system is used.
.br
.SH RETURN VALUE
\fBaddbddvarbefore\fP returns a pointer to the \fBbdd\fP node of the new variable.
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"no more variables, error !"
.ft R
.RS
There is no variable number left.
.RE
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"index xxx out of range, error !"
.ft R
.RS
The \fIIndex\fP parameter must be a valid index.
.RE
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "bdd101.h"
   bddsystem  \(**BddSystem;
   bddnode    \(**BddNode1;
   bddnode    \(**BddNode2;
   BddSystem  = createbddsystem( 100, 1000, 100, 50000 );
   BddNode1 = addbddvarfirst( (bddsystem \(**)0 );
   BddNode2 = addbddvarbefore( (bddsystem \(**)0, BddNode1->INDEX );
   destroybddsystem( (bddsystem \(**)0 );
.ft R
.fi
.SH SEE ALSO
.BR bdd (1)


.so man1/alc_bug_report.1

