.\"   $Id: getbddvarindex.3,v 1.1.1.1 2002/03/18 11:26:50 ludo Exp $
.\" @(#)getbddvarindex.2 2.7 96/07/02 ; Labo masi cao-vlsi; Author : Jacomme Ludovic
.TH GETBDDVARINDEX 3 "October 1, 1997" "ASIM/LIP6" "BDD FUNCTIONS"
.SH NAME
getbddvarindex \- converts a variable number in a \fBbdd\fP index.
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "bdd101.h"
bddindex getbddvarindex( BddSystem, Variable )
  bddsystem \(**BddSystem;
  bddvar     Variable;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIBddSystem\fP
The \fBbdd\fP system.
.TP
\fIVariable\fP
The variable number to convert.
.SH DESCRIPTION
\fBgetbddvarindex\fP converts the variable number \fIVariable\fP
to a \fBbdd\fP index, in the \fBbdd\fP system \fIBddSystem\fP.
If a null pointer is given, the default \fBbdd\fP system is used.
The function uses simply the translation table \fIBddSystem\fP->VAR_TO_INDEX.
.br
.SH RETURN VALUE
\fBgetbddvarindex\fP returns the \fBbdd\fP index of \fIVariable\fP.
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"variable xxx out of range, error !"
.ft R
.RS
The \fIVariable\fP parameter must be less or equal to
the \fIBddSystem->NUMBER_VAR\fP field.
.RE
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "bdd101.h"
   bddsystem  \(**BddSystem;
   bddnode    \(**BddNode;
   BddSystem  = createbddsystem( 100, 1000, 100, 50000 );
   BddNode = addbddvar( (bddsystem \(**)0, 0 );
   /* displays 2 */
   printf( "%d", getbddvarindex( (bddsystem \(**)0, 0 ) );
   destroybddsystem( (bddsystem \(**)0 );
.ft R
.fi
.SH SEE ALSO
.BR bdd (1)


.so man1/alc_bug_report.1

