.\"   $Id: resetbddsystem.3,v 1.1.1.1 2002/03/18 11:26:51 ludo Exp $
.\" @(#)resetbddsystem.2 2.7 96/07/02 ; Labo masi cao-vlsi; Author : Jacomme Ludovic
.TH RESETBDDSYSTEM 3 "October 1, 1997" "ASIM/LIP6" "BDD FUNCTIONS"
.SH NAME
resetbddsystem \- resets a \fBbdd\fP system.
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "bdd101.h"
void resetbddsystem( BddSystem )
  bddsystem \(**BddSystem;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIBddSystem\fP
The \fBbdd\fP system to reset.
.SH DESCRIPTION
\fBresetbddsystem\fP resets the \fBbdd\fP system \fIBddSystem\fP.
If a null pointer is given, the default \fBbdd\fP system is used.
.br
.SH RETURN VALUE
\fBresetbddsystem\fP returns nothing.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "bdd101.h"
   bddsystem \(**BddSystem;
   BddSystem = createbddsystem( 100, 1000, 100, 50000 );
   ...
   resetbddsystem( (bddsystem \(**)0 );
   destroybddsystem( BddSystem );
.ft R
.fi
.SH SEE ALSO
.BR bdd (1)
.BR createbddsytem(3),
.BR destroybddsytem(3).


.so man1/alc_bug_report.1

