.\"   $Id: MBK_IN_LO.1,v 1.2 2002/10/09 20:12:43 xtof Exp $
.\" @(#)MBK_IN_LO.8 2.11 91/08/22; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
MBK_IN_LO
.XE \}
.TH MBK_IN_LO 1 "October 1, 1997" "ASIM/LIP6" "MBK ENVIRONMENT VARIABLES"
.SH NAME
MBK_IN_LO \- define the logical input format of mbk and genlib
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
c-shell running
setenv MBK_IN_LO format
.ft R
.fi
.so man1/alc_origin.1
.SH DESCRIPTION
\fBMBK_IN_LO\fP sets the logical input format of the mbk database. The database
will be filled with informations found in the given format file.
.TP
valid formats are :
\- \fBal\fP, \fBalx\fP, that are alliance logical formats
.br
\- \fBedi\fP, that is edif standart netlist format
.br
\- \fBhns\fP, \fBfns\fP, \fBfne\fP, \fBfdn\fP, \fBhdn\fP, that are vti logical
formats
.br
\- \fBspi\fP, that's spice netlist
.br
\- \fBvst\fP, that structural vhdl description
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"MBK_IN_LO : 'xxx' unknown format"
.ft R
.RS
The argument given to the setenv is not a legal logical input format for mbk.
You must changed it before any other action.
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
	setenv MBK_IN_LO al
.ft R
.fi
.SH SEE ALSO
.BR mbk (3),
.BR genlib (1),
.BR MBK_OUT_LO (1).


.so man1/alc_bug_report.1

