.\"   $Id: MBK_CK.1,v 1.1 2003/04/03 14:55:09 xtof Exp $
.\" @(#)MBK_CK.8 2.11 91/08/22; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
MBK_CK
.XE \}
.TH MBK_CK 1 "October 1, 1997" "ASIM/LIP6" "MBK ENVIRONMENT VARIABLES"
.SH NAME
MBK_CK \- define the clock name pattern
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
c-shell running
setenv MBK_CK cke
.ft R
.fi
.so man1/alc_origin.1
.SH DESCRIPTION
\fBMBK_CK\fP sets the pattern to be matched in a name to indicate a clock 
for the tools based upon \fBmbk\fP.
Its default value is \fBck\fP.
Therefore all names of the form `*\fBck\fP*' indicates a clock.
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
	setenv MBK_CK vcc
.ft R
.fi
.SH SEE ALSO
.BR mbk (3),
.BR genlib (1),
.BR isvdd (3),
.BR isvss (3),
.BR isck(3),
.BR MBK_VSS (1),
.BR MBK_VDD (1).


.so man1/alc_bug_report.1

