.\"   $Id: MBK_VDD.1,v 1.2 2002/10/09 20:12:43 xtof Exp $
.\" @(#)MBK_VDD.8 2.11 91/08/22; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
MBK_VDD
.XE \}
.TH MBK_VDD 1 "October 1, 1997" "ASIM/LIP6" "MBK ENVIRONMENT VARIABLES"
.SH NAME
MBK_VDD \- define the high level power name pattern
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
c-shell running
setenv MBK_VDD powername
.ft R
.fi
.so man1/alc_origin.1
.SH DESCRIPTION
\fBMBK_VDD\fP sets the pattern to be matched in a name to indicate a power
supply for the tools based upon \fBmbk\fP.
Its default value is \fBvdd\fP.
Therefore all names of the form `*\fBvdd\fP*' indicates a power supply.
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
	setenv MBK_VDD vcc
.ft R
.fi
.SH SEE ALSO
.BR mbk (3),
.BR genlib (1),
.BR isvdd (3),
.BR isvss (3),
.BR MBK_VSS (1).


.so man1/alc_bug_report.1

