.\"   $Id: MBK_OUT_PH.1,v 1.2 2002/10/09 20:12:43 xtof Exp $
.\" @(#)MBK_OUT_PH.8 2.11 91/08/22; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
MBK_OUT_PH
.XE \}
.TH MBK_OUT_PH 1 "October 1, 1997" "ASIM/LIP6" "MBK ENVIRONMENT VARIABLES"
.SH NAME
MBK_OUT_PH \- define the physical output format of mbk and genlib
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
c-shell running
setenv MBK_OUT_PH format
.ft R
.fi
.so man1/alc_origin.1
.SH DESCRIPTION
\fBMBK_OUT_PH\fP sets the physical output format of the mbk data structure.
The files resulting of the work on mbk will have the given format. 
.TP
valid formats are :
\- \fBap\fP, for alliance physical output
.br
\- \fBcp\fP, in order to obtain a vti physical file
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"MBK_OUT_PH : 'xxx' unknown format"
.ft R
.RS
The argument given to the setenv is not a legal physical output format for mbk.
You must changed it before any other action.
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
	setenv MBK_OUT_PH al
.ft R
.fi
.SH SEE ALSO
.BR mbk (3),
.BR genlib (1),
.BR MBK_IN_PH (1).


.so man1/alc_bug_report.1

