.\"   $Id: MBK_SEPAR.1,v 1.2 2002/10/09 20:12:43 xtof Exp $
.\" @(#)MBK_SEPAR.8 2.11 91/08/22; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
MBK_SEPAR
.XE \}
.TH MBK_SEPAR 1 "October 1, 1997" "ASIM/LIP6" "MBK ENVIRONMENT VARIABLES"
.SH NAME
MBK_SEPAR \- define the separator character for hierarchy
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
c-shell running
setenv MBK_SEPAR character
.ft R
.fi
.so man1/alc_origin.1
.SH DESCRIPTION
\fBMBK_SEPAR\fP sets the character that is to be used while concatening
names, during a flatten, for example.
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
	setenv MBK_SEPAR /
.ft R
.fi
.SH SEE ALSO
.BR mbk (3),
.BR genlib (1),
.BR concatname (3),
.BR nameindex (3).


.so man1/alc_bug_report.1

