.\"   $Id: MBK_WORK_LIB.1,v 1.2 2002/10/09 20:12:43 xtof Exp $
.\" @(#)MBK_WORK_LIB.8 2.11 91/08/22; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
MBK_WORK_LIB
.XE \}
.TH MBK_WORK_LIB 1 "October 1, 1997" "ASIM/LIP6" "MBK ENVIRONMENT VARIABLES"
.SH NAME
MBK_WORK_LIB \- define the mbk working directory
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
c-shell running
setenv MBK_WORK_LIB unix path
.ft R
.fi
.so man1/alc_origin.1
.SH DESCRIPTION
\fBMBK_WORK_LIB\fP sets the directory where are saved the results of an
invocation of mbk or genlib. This directory is considered to be, from an
mbk point of view, read and write.
.br
Also, when a file is searched for
reading, the first directory to be looked at is the \fBMBK_WORK_LIB\fP, and then
the one defined in \fBMBK_CATA_LIB\fP(1).
.br
The unix path argument must be a actually accessible path on your host machine.
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"mbk_fopen : can't open file 'unix_path/file.xx'"
.ft R
.RS
This occurs when either the unix path is irrelevent, or when the file doesn't
exist if it is open for reading, or when you don't have the right on the file
or directory while trying to write it.
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
	setenv MBK_WORK_LIB ~fred/crechan/uom
.ft R
.fi
.SH SEE ALSO
.BR mbk (3),
.BR genlib (1),
.BR MBK_CATA_LIB (1).


.so man1/alc_bug_report.1

