.\"   $Id: MBK_CATAL_NAME.1,v 1.2 2002/10/09 20:12:43 xtof Exp $
.\" @(#)MBK_CATAL_NAME.8 2.11 91/08/22; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
MBK_CATAL_NAME
.XE \}
.TH MBK_CATAL_NAME 1 "October 1, 1997" "ASIM/LIP6" "MBK ENVIRONMENT VARIABLES"
.SH NAME
MBK_CATAL_NAME \- define the mbk catalog file
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
c-shell running
setenv MBK_CATAL_NAME file
.ft R
.fi
.so man1/alc_origin.1
.SH DESCRIPTION
\fBMBK_CATAL_NAME\fP sets the name of the catalog file, that contains
information about the cells of a design. The catalog file syntax is a cellname, 
plus a flag. The cellname may appear many times with a different flag.
.TP
Three flags are available:
  C : tells the flatten functions to stop a this level.
.br
  G : informs the user that this is a phantom cell.
.br
  F : says that this is a feed through.
.br
The seaching mecanism first look in \fBMBK_WORK_LIB\fP(1), and then
in \fBMBK_CATA_LIB\fP(1). So it is recommended to have a catalog file in
the \fBMBK_WORK_LIB\fP(1).
.br
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
	setenv MBK_CATAL_NAME catalog
.ft R
.fi
.SH SEE ALSO
.BR mbk (5),
.BR genlib (1).


.so man1/alc_bug_report.1

