.\" $Id: alc_origin.1,v 1.4 2004/07/27 19:37:59 fred Exp $
.\" 
.\" Generic header for alliance man pages
.\" 
 
.SH ORIGIN
This software belongs to the \f4 ALLIANCE CAD SYSTEM\fP developed by 
the ASIM team at 
.B LIP6
laboratory of Université Pierre et Marie CURIE, in Paris, France. 

.br
Web :
.I http://asim.lip6.fr/recherche/alliance/
.br
E-mail : 
.I alliance\-users@asim.lip6.fr
