.\"   $Id: DEF_GENPAT.3,v 1.1 2002/05/31 08:27:45 xtof Exp $
.\" @(#)DEF_GENPAT.3 2.30  UPMC ; VUONG H.N.
.TH DEF_GENPAT 3 "October 1, 1997" "ASIM/LIP6" "GENPAT functions"

.SH NAME
.PP
\fBDEF_GENPAT\fP, GENPAT Package

.so man1/alc_origin.1
.SH SYNOPSYS
.PP
.nf
DEF_GENPAT ("ident");
.fi

.SH PARAMETERS
.PP
.TP 10
\fIident\fP
Output file's name without extension.

.SH DESCRIPTION
.PP
Gives the output file's name.

.SH EXAMPLE
.PP
.nf
DEF_GENPAT ("my_file");
Declares the output file's name as my_file.<VH_PATSFX>, usually my_file.pat.
.fi

.SH SEE ALSO
.PP
SAV_GENPAT(3), genpat(1), pat(5)


.so man1/alc_bug_report.1

