.\"   $Id: GETCPAT.3,v 1.1 2002/05/31 08:27:45 xtof Exp $
.\" @(#)LABEL.3 2.30  UPMC ; PITON D.
.TH GETCPAT 3 "October 1, 1997" "ASIM/LIP6" "GENPAT functions"

.SH NAME
.PP
\fBGETCPAT\fP, GENPAT Package

.so man1/alc_origin.1
.SH SYNOPSIS
.PP
.nf
GETCPAT();
.fi

.SH DESCRIPTION
.PP
Return the date of the current pattern (in ps). The current pattern is
set by AFFECT or INIT, GETCPAT will return the date of the last modified
(affected or initialised) pattern. 

.SH EXAMPLE
.PP
.nf
int t;
t = GETCPAT();
.fi

.SH SEE ALSO
.PP
genpat(1), pat(5), AFFECT(3)


.so man1/alc_bug_report.1

