.\"   $Id: LABEL.3,v 1.1 2002/05/31 08:27:45 xtof Exp $
.\" @(#)LABEL.3 2.30  UPMC ; VUONG H.N. & PITON D.
.TH LABEL 3 "October 1, 1997" "ASIM/LIP6" "GENPAT functions"

.SH NAME
.PP
\fBLABEL\fP, GENPAT Package

.so man1/alc_origin.1
.SH SYNOPSYS
.PP
.nf
LABEL ("ident");
.fi

.SH PARAMETERS
.PP
.TP 10
\fIident\fP
label to be put on the current pattern (last modified using INIT or AFFECT)

.SH DESCRIPTION
.PP
Set \fIident\fP as the label of the current pattern.

.SH EXAMPLE
.PP
.nf
LABEL ("foo");
.fi

.SH WARNING
.PP
The LABEL fonction from the 1.9 release doesn't have the same behaviour.

.SH SEE ALSO
.PP
genpat(1), pat(5), AFFECT(3)


.so man1/alc_bug_report.1

