.\"   $Id: SAVE.3,v 1.1 2002/05/31 08:27:46 xtof Exp $
.\" @(#)SAVE.3 2.30 Sep 09 1993 UPMC ; VUONG H.N. 
.TH SAVE 3 "October 1, 1997" "ASIM/LIP6" "GENPAT functions"

.SH NAME
.PP
\fBSAVE\fP, GENPAT Package

.SH SYNOPSYS
.PP
.nf
SAVE ();
.fi

.so man1/alc_origin.1
.SH DESCRIPTION
.PP
Make the simulator to save the state of the circuit at the end of the
simulation.

.SH EXAMPLES
.PP
.nf
SAVE ();
.fi

.SH SEE ALSO
.PP
genpat(1), pat(5), asimut(1)


.so man1/alc_bug_report.1

