.TH PAT2DWL 1 "October 1, 1997" "ASIM/LIP6" "CAO\-VLSI Reference Manual"
.SH NAME
.PP
\fIk2f\fP, FSM translator ALLIANCE format from/to Berkeley format

.so man1/alc_origin.1
.SH SYNOPSIS
.PP
\fBk2f\fP 
.I In_format
.I Out_format
.I Input_name
[
.I Output_name
]

.SH DESCRIPTION
.PP
\fBk2f\fP is a FSM translator from ALLIANCE format (\fI".fsm"\fP)
to Berkeley format (\fI".kiss2"\fP).

.SH SEE ALSO
.PP
fsm(5)


.so man1/alc_bug_report.1

