.\"   $Id: catal.5,v 1.3 2002/12/11 14:29:03 xtof Exp $
.\" @(#)catal.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.TH CATAL 5 "October 1, 1997" "ASIM/LIP6" "ALLIANCE FILE FORMATS"
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
catal
.XE \}
.SH NAME
catal \- catalog file format
.so man1/alc_origin.1
.SH DESCRIPTION
.TP 
Predefined libraries
The environment variable \fBMBK_CATA_LIB\fP(1) defines several paths
corresponding to the \fIAlliance\fP predefined cell libraries.
Each library is in one unix directory.
.RS
.TP 20
\fIsxlib\fP
standard cell library
.TP 20
\fIdp_sxlib\fP
data-path compiler library
.TP 20
\fIrflib\fP
registers library
.TP 20
\fIramlib\fP
ram library
.TP 20
\fIromlib\fP
rom library
.TP 20
\fIpadlib\fP
pads lib
.TP 20
For each library, a special file named \fBCATAL\fP describes the library
contents.
This file must be in the same directory as the library cells.
For the \fBAlliance\fP tools, the cells described in the predefined libraries
are read only.
.RE
.TP
The working library
The environment variable \fBMBK_WORK_LIB\fP(1) defines the current working
directory.
Its default value is \fB.\fP (dot).
This directory will contain the user cells, seen as read write by the
\fIAlliance\fP tools.
It is not necessary to describe all the user cells in a catalog file.
But the user can locally define a catalog file for the working library.
The local catalog file name is set by the environment variable
\fBMBK_CATAL_NAME\fP(1), \fBCATAL\fP by default.
\fIAlliance\fP will concatenate all catalog files of the predefined libraries
and the optional catalog file of the working library to access the attributs
of each cell.
.TP
Cells attributs
A cell may be characterized by four attributs:
.RS
.TP 20
\fBC\fP
this attribut means that the cell is a leaf cell in the context of a recursive
flatten, for either the layout or netlist view.
The cell will not be flattened.
.TP
\fBG\fP
this attribut means that the cell has an existing equivalent \fIGDS\fP or
\fICIF\fP representation.
It is used by the symbolic to real translation tool, \fBs2r\fP(1), to
make direct replacements.
.TP
\fBF\fP
this attribut means that the cell is used as a feed through.
.TP
\fBD\fP
this attribut is used only in the user defined catalog.
As the user is not allowed to delete a cell in a predefined library, it is 
possible to virtually remove a cell of a predefined library with the \fBD\fP
attribut in the user defined catalog.
.RE
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
a2_y    C
a2p_y   C
a3_y    C
a3p_y   C
n1_y    C
na2_y   C
p1_y    C
tie_y   C
	\&.
	\&.
	\&.
p1_y    G
	\&.
	\&.
	\&.
tie_y   F
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR sxlib (1),
.BR incatalog (3),
.BR incatalogdelete (3),
.BR incatalogfeed (3),
.BR incataloggds (3),
.BR MBK_CATA_LIB (1),
.BR MBK_CATAL_NAME (1),
.BR MBK_WORK_LIB (1).


.so man1/alc_bug_report.1

