.\"   $Id: addcapa.3,v 1.1.1.1 2002/03/08 13:51:00 fred Exp $
.\" @(#)addcapa.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
addcapa
.XE \}
.TH ADDCAPA 3 "October 1, 1997" "ASIM/LIP6" "MBK LOGICAL FUNCTIONS"
.SH NAME
addcapa \- add a capacitance to a signal
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"
void addcapa(ptsig, ctot)
losig_list \(**ptsig;
float ctot;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIptfig\fP
Pointer to the signal in which the capacitance should be added
.TP
\fIctot\fP
Total capacitance
.SH DESCRIPTION
\fBaddcapa\fP add the \fIcapa\fP value to \fIptsig\->CAPA\fP.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"
void more_capa(pt, i, c)
lofig_list \(**pt;
long i;
float c;
{
	addcapa(getlosig(pt, i), c);
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR losig (3).


.so man1/alc_bug_report.1

