.\"   $Id: append.3,v 1.1.1.1 2002/03/08 13:51:01 fred Exp $
.\" @(#)append.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
append
.XE
.XS4 \n%
.ti 0.2i
append
.XE4 \}
.TH APPEND 3 "October 1, 1997" "ASIM/LIP6" "MBK UTILITY FUNCTIONS"
.SH NAME
append \- append a \fBchain_list\fP to an other \fBchain_list\fP
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mut.h"
chain_list \(**append(pt1, pt2)
chain_list \(**pt1,\(**pt2;	
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIpt1\fP
Pointer to a \fBchain_list\fP
.TP
\fIpt2\fP
Pointer to a \fBchain_list\fP
.SH DESCRIPTION
\fBappend\fP appends the contains of the \fBchain_list\fP pointed to by
\fIpt2\fP at the end of the one pointed to by \fIpt1\fP.
.br
The lists consistency is warranted by the use of the adequat \fBadd\fI
functions.
.SH RETURN VALUE
\fBappend\fP returns a pointer to the new head of list.
If \fIpt1\fP is not \fBNULL\fP, it has the value of \fIpt1\fP, else it is
\fIpt2\fP.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mut.h"
#include "mlo.h"
void sig_names(s0, s1)
losig_list \(**s0, \(**s1;
{
	s0\->NAMECHAIN = append(s0\->NAMECHAIN, s1\->NAMECHAIN);
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR chain (3).


.so man1/alc_bug_report.1

