.\"   $Id: concatname.3,v 1.1.1.1 2002/03/08 13:51:01 fred Exp $
.\" @(#)concatname.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
concatname
.XE
.XS4 \n%
.ti 0.2i
concatname
.XE4 \}
.TH CONCATNAME 3 "October 1, 1997" "ASIM/LIP6" "MBK UTILITY FUNCTIONS"
.SH NAME
concatname \- concatenate two names with user separator
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mut.h"
char \(**concatname(s, t)
char \(**s, \(**t;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIs\fP
Pointer to a string
.TP
\fIt\fP
Pointer to a string
.SH DESCRIPTION
The \fBconcatname\fP function adds the separator defined by \fBMBK_SEPAR\fP(1),
and then the string \fIt\fP at the end of string \fIs\fP. This is not like a
\fBstrcat\fP(3) of the standard library, because \fIs\fP is not beeing modified.
The string returned has already been put in the names dictionary by
a call to \fBnamealloc\fP(3).
.SH RETURN VALUE
\fBconcatname\fP returns a pointer to a string in the name hash table.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mut.h"
#include "mlo.h"
void flat_sig_alias(ptsig, insname)
losig_list \(**ptsig;
char \(**insname;
{
chain_list \(**pt;
	for (pt = ptsig\->NAMECHAIN; pt; pt = pt\->NEXT)
		pt\->DATA = (void \(**)concatname(insname, (char \(**)pt\->DATA);
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR namealloc (3),
.BR MBK_SEPAR (1).


.so man1/alc_bug_report.1

