.\"   $Id: defab.3,v 1.1.1.1 2002/03/08 13:51:01 fred Exp $
.\" @(#)defab.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
defab
.XE \}
.TH DEFAB 3 "October 1, 1997" "ASIM/LIP6" "MBK PHYSICAL FUNCTIONS"
.SH NAME
defab \- defines the \fIabutment box\fP of a \fBphfig\fP
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mph.h"
void defab(ptfig, x1, y1, x2, y2)
phfig_list \(**ptfig;
long x1, x2, y1, y2;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIptfig\fP
Pointer to a \fBphfig\fP
.TP
\fIx1, y1, x2, y2\fP
Coordinates of the \fIabutment box\fP
.SH DESCRIPTION
\fBdefab\fP redefines the \fIabutment box\fP of the figure pointed to by
\fIptfig\fP.
It overwrite any existing value in the \fIXAB1\fP, \fIYAB1\fP, \fIXAB2\fP and
\fIYAB2\fP by the given arguments.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mph.h"
void add_half_rules(fig)
phfig_list \(**fig;
{
	defab(fig, fig\->XAB1 + HALF_RULE, fig\->YAB1 + HALF_RULE,
		fig\->XAB2 + HALF_RULE, fig\->YAB2 + HALF_RULE);
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR phfig (3).


.so man1/alc_bug_report.1

