.\"   $Id: dellocon.3,v 1.1.1.1 2002/03/08 13:51:01 fred Exp $
.\" @(#)dellocon.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
dellocon
.XE
.XS2 \n%
.ti 0.2i
dellocon
.XE2 \}
.TH DELLOCON 3 "October 1, 1997" "ASIM/LIP6" "MBK LOGICAL FUNCTIONS"
.SH NAME
dellocon \- delete a logical connector
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"
int dellocon(ptfig, name)
lofig_list \(**ptfig;
char \(**name;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIptfig\fP
Pointer to the figure in which the connector should be deleted
.TP
\fIname\fP
Name of the connector to be deleted.
.SH DESCRIPTION
\fBdellocon\fP deletes the connector called \fIname\fP in the figure 
pointed to by \fIptfig\fP. The list consistency is maintained, and the space
freed.
.SH RETURN VALUE
\fBdellocon\fP returns \fB1\fP if the connector has been deleted, \fB0\fP
if no such connector exists in the list.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"
char \(**was_existing(p, s)
lofig_list \(**p;
char \(**s;
{
   return dellocon(p, s) ? "you just killed it!\n" 
                         : "wasn't here anyway\n"; 
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR lofig (3),
.BR locon (3),
.BR addlocon (3),
.BR getlocon (3).


.so man1/alc_bug_report.1

