.\"   $Id: dellores.3,v 1.1 2002/08/14 21:47:47 pnt Exp $
.\" @(#)dellores.2 2.11 91/08/22 ; Labo LIP6/ASIM cao-vlsi; Author : Pierre Nguyen Tuong
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
dellores
.XE
.XS2 \n%
.ti 0.2i
dellores
.XE2 \}
.TH DELLORES 3 "August 14, 2002" "ASIM/LIP6" "MBK LOGICAL FUNCTIONS"
.SH NAME
dellores \- delete a logical resistor
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"

int dellores(ptfig,ptres)
lofig_list \(**ptfig ;
lores_list \(**ptres ;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIptfig\fP
Pointer to the figure in which the resistor should be deleted
.TP
\fIptres\fP
Pointer to the resistor to be deleted.
.SH DESCRIPTION
\fBdellores\fP delete the resistor pointed to by \fIptres\fP in the figure 
pointed to by \fIptfig\fP. 
The list consistency is maintainded, and the space freed. The resistor
connectors are also freed, since if the resistor disapear,
no more connections can occur on it.
.SH RETURN VALUE
\fBdellores\fP returns \fB1\fP if the resistor has been deleted, \fB0\fP
if the resistor pointer does not exists in the list.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"

char \(**was_existing(lofig_list \(**ptfig,lores_list \(**ptres)
{
  return dellores(ptfig,ptres) ? "you just killed it!" : "wasn't here anyway" ; 
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR lofig (3),
.BR lores (3),
.BR addlores (3).


.so man1/alc_bug_report.1

