.\"   $Id: dellosig.3,v 1.1.1.1 2002/03/08 13:51:01 fred Exp $
.\" @(#)dellosig.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
dellosig
.XE
.XS2 \n%
.ti 0.2i
dellosig
.XE2 \}
.TH DELLOSIG 3 "October 1, 1997" "ASIM/LIP6" "MBK LOGICAL FUNCTIONS"
.SH NAME
dellosig \- delete a logical signal
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"
int dellosig(ptfig, index)
lofig_list \(**ptfig;
long index;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIptfig\fP
Pointer to the figure in which the signal should be deleted
.TP
\fIindex\fP
Index of the signal to be deleted.
.SH DESCRIPTION
\fBdellosig\fP delete the signal that has \fIindex\fP as \fIINDEX\fP 
in the figure pointed to by \fIptfig\fP. 
The list consistency is maintainded, and the space freed.
.SH RETURN VALUE
\fBdellosig\fP returns \fB1\fP if the signal has been deleted, \fB0\fP
if the signal index does not exists in the list.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"
char \(**was_existing(ptfig, index)
lofig_list \(**ptfig;
long index;
{
   return dellosig(ptfig, index) ? "you just killed it!"
                                 : "wasn't here anyway"; 
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR lofig (3),
.BR losig (3),
.BR addlosig (3),
.BR getlosig (3).


.so man1/alc_bug_report.1

