.\"   $Id: delphfig.3,v 1.1.1.1 2002/03/08 13:51:01 fred Exp $
.\" @(#)delphfig.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
delphfig
.XE
.XS0 \n%
.ti 0.2i
delphfig
.XE0 \}
.TH DELPHFIG 3 "October 1, 1997" "ASIM/LIP6" "MBK PHYSICAL FUNCTIONS"
.SH NAME
delphfig \- delete and free a physical figure 
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mph.h"
int delphfig(figname)
char \(**figname;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIfigname\fP
Name of the figure to be deleted
.SH DESCRIPTION
\fBdelphfig\fP deletes the figure called \fIfigname\fP from the list of
physical figure in memory. All the lists of elements belonging to the figure
are also deleted and freed.
.SH RETURN VALUE
\fBdelphfig\fP returns \fB1\fP if the figure was delete, and \fB0\fP if no
figure called \fIfigname\fP was present in memory.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mph.h"
void delete_na2_y()
{
	if (delphfig("na2_y"))
		(void)fputs("deleted na2_y successfully", stdout);
	else
		(void)fputs("na2_y not present in ram !", stdout);		
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR phfig (3),
.BR addphfig (3),
.BR getphfig (3),
.BR loadphfig (3),
.BR savephfig (3),
.BR flattenphfig (3),
.BR rflattenphfig (3).


.so man1/alc_bug_report.1

