.\"   $Id: delphref.3,v 1.1.1.1 2002/03/08 13:51:01 fred Exp $
.\" @(#)delphref.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
delphref
.XE
.XS0 \n%
.ti 0.2i
delphref
.XE0 \}
.TH DELPHREF 3 "October 1, 1997" "ASIM/LIP6" "MBK PHYSICAL FUNCTIONS"
.SH NAME
delphref \- delete a physical reference
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mph.h"
int delphref(ptfig, ptref)
phfig_list \(**ptfig;
phref_list \(**ptref;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIptfig\fP
Pointer to the figure in which the reference should be deleted
.TP
\fIptref\fP
Pointer to the reference to be deleted.
.SH DESCRIPTION
\fBdelphref\fP delete the reference pointed to by \fIptref\fP in the figure 
pointed to by \fIptfig\fP.
The list consistency is maintainded, and the space freed.
.SH RETURN VALUE
\fBdelphref\fP returns \fB1\fP if the reference has been deleted, \fB0\fP
if no such reference exists in the list.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mph.h"
char \(**was_existing(ptfig, ptref)
phfig_list \(**ptfig;
phref_list \(**ptref;
{
   /\(** if only one exists, it's this one \(**/
   return delphref(ptfig, ptref) ? "you just killed it!"
                                 : "wasn't here anyway"; 
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR phfig (3),
.BR phref (3),
.BR addphref (3),
.BR getphref (3).


.so man1/alc_bug_report.1

