.\"   $Id: delphcon.3,v 1.1.1.1 2002/03/08 13:51:01 fred Exp $
.\" @(#)delphcon.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
delphcon
.XE
.XS0 \n%
.ti 0.2i
delphcon
.XE0 \}
.TH DELPHCON 3 "October 1, 1997" "ASIM/LIP6" "MBK PHYSICAL FUNCTIONS"
.SH NAME
delphcon \- delete a physical connector
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mph.h"
int delphcon(ptfig, ptcon)
phfig_list \(**ptfig;
phcon_list \(**ptcon;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIptfig\fP
Pointer to the figure in which the connector should be deleted
.TP
\fIptcon\fP
Pointer to the connector to be deleted.
.SH DESCRIPTION
\fBdelphcon\fP delete the connector pointed to by \fIptcon\fP in the figure 
pointed to by \fIptfig\fP.
The list and index consistency is maintainded, and the space freed.
.SH RETURN VALUE
\fBdelphcon\fP returns \fB1\fP if the connector has been deleted, \fB0\fP
if no such connector exists in the list.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mph.h"
char \(**was_existing(ptfig, ptcon)
phfig_list \(**ptfig;
phcon_list \(**ptcon;
{
   /\(** if only one exists, it's this one \(**/
   return delphcon(ptfig, ptcon) ? "you just killed it!\n"
                                 : "wasn't here anyway\n"; 
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR phfig (3),
.BR phcon (3),
.BR addphcon (3),
.BR getphcon (3).


.so man1/alc_bug_report.1

