.\"   $Id: freelomodel.3,v 1.1.1.1 2002/03/08 13:51:02 fred Exp $
.\" @(#)freelomodel.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
freelomodel
.XE
.XS2 \n%
.ti 0.2i
freelomodel
.XE2 \}
.TH FREELOMODEL 3 "October 1, 1997" "ASIM/LIP6" "MBK LOGICAL FUNCTIONS"
.SH NAME
freelomodel \- free a \fBlofig_list\fP for temporary models
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"
void freelomodel(ptmodel)
lofig_list \(**ptmodel;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIptmodel\fP
Pointer to the model list to be freed
.SH DESCRIPTION
\fBfreelomodel\fP free the \fBlofig_list\fP pointed to by \fIptmodel\fP.
All the elements of the list are given back to the system.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"
void end_of_parse() /\(** erase model list \(**/
{
	freelomodel(MODEL);
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR lofig (3),
.BR addlomodel (3),
.BR getlomodel (3).


.so man1/alc_bug_report.1

