.\"   $Id: getlocap.3,v 1.3 2002/08/16 19:19:41 pnt Exp $
.\" @(#)getlocap.2 2.11 2002/08/14 ; Labo LIP6/ASIM cao-vlsi; Author : Pierre Nguyen Tuong
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
getlocap
.XE
.XS2 \n%
.ti 0.2i
getlocap
.XE2 \}
.TH GETLOCAP 3 "August 14, 2002" "ASIM/LIP6" "MBK LOGICAL FUNCTIONS"
.SH NAME
getlocap \- retrieve a logical capacitor
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"

locap_list \(**getlocap(ptfig,name)
lofig_list \(**ptfig ;
const char \(**name ;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIptfig\fP
Pointer to the figure in which the capacitor should be seeked
.TP
\fIname\fP
Instance name of the capacitor
.SH DESCRIPTION
\fBgetlocap\fP looks in the list of capacitors of the logical model pointed
to by \fIptfig\fP for a capacitor identified by its instance \fIname\fP.
.SH RETURN VALUE
\fBgetlocap\fP returns a pointer to the given capacitor.
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"\(**\(**\(** mbk error \(**\(**\(** getlocap impossible :
capacitor \fIname\fP doesn't exist in figure \fIptfig \-> NAME\fP"
.ft R
.RS
No capacitor matches the name. 
.RE
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"

locap_list \(**exist(char \(**figname,char \(**capname)
{
  return getlocap(getlofig(figname,'A'),capname) ;
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR lofig (3),
.BR locap (3),
.BR addlocap (3),
.BR setlocap (3),
.BR dellocap (3).


.so man1/alc_bug_report.1

