.\"   $Id: getlores.3,v 1.2 2002/08/16 19:19:41 pnt Exp $
.\" @(#)getlores.2 2.11 2002/08/14 ; Labo LIP6/ASIM cao-vlsi; Author : Pierre Nguyen Tuong
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
getlores
.XE
.XS2 \n%
.ti 0.2i
getlores
.XE2 \}
.TH GETLORES 3 "August 14, 2002" "ASIM/LIP6" "MBK LOGICAL FUNCTIONS"
.SH NAME
getlores \- retrieve a logical resistor
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"

lores_list \(**getlores(ptfig,name)
lofig_list \(**ptfig ;
const char \(**name ;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIptfig\fP
Pointer to the figure in which the resistor should be seeked
.TP
\fIname\fP
Instance name of the resistor
.SH DESCRIPTION
\fBgetlores\fP looks in the list of resistors of the logical model pointed
to by \fIptfig\fP for a resistor identified by its instance \fIname\fP.
.SH RETURN VALUE
\fBgetlores\fP returns a pointer to the given resistor.
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"\(**\(**\(** mbk error \(**\(**\(** getlores impossible :
resistor \fIname\fP doesn't exist in figure \fIptfig \-> NAME\fP"
.ft R
.RS
No resistor matches the name. 
.RE
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"

lores_list \(**exist(char \(**figname,char \(**resname)
{
  return getlores(getlofig(figname,'A'),resname) ;
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR lofig (3),
.BR lores (3),
.BR addlores (3),
.BR dellores (3).


.so man1/alc_bug_report.1

