.\"   $Id: getphins.3,v 1.1.1.1 2002/03/08 13:51:02 fred Exp $
.\" @(#)getphins.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
getphins
.XE
.XS0 \n%
.ti 0.2i
getphins
.XE0 \}
.TH GETPHINS 3 "October 1, 1997" "ASIM/LIP6" "MBK PHYSICAL FUNCTIONS"
.SH NAME
getphins \- retrieve a physical instance
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mph.h"
phins_list \(**getphins(ptfig, insname)
phfig_list \(**ptfig;
char \(**insname;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIptfig\fP
Pointer to the figure in which the instance should be seeked
.TP
\fIinsname\fP
Name of the instance
.SH DESCRIPTION
\fBgetphins\fP looks in the list of instances of the physical model pointed
to by \fIptfig\fP for a instance identified by its \fIinsname\fP.
.SH RETURN VALUE
\fBgetphins\fP returns a pointer to the instance that matches the
\fIinsname\fP.
.SH ERROR
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"\(**\(**\(** mbk error \(**\(**\(** illegal getphins instance \fIinsname\fP doesn't exist
in figure \fIptfig\->NAME\fP" 
.ft R
.RS
No instance is called \fIinsname\fP in the figure. 
.RE
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mph.h"
phins_list \(**exist(figname, insname)
char \(**figname, \(**insname;
{
   return getphins(getphfig(figname), insname);   
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR phfig (3),
.BR phins (3),
.BR addphins (3),
.BR delphins (3).


.so man1/alc_bug_report.1

