.\"   $Id: getsigname.3,v 1.1.1.1 2002/03/08 13:51:02 fred Exp $
.\" @(#)getsigname.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
getsigname
.XE \}
.TH GETSIGNAME 3 "October 1, 1997" "ASIM/LIP6" "MBK LOGICAL FUNCTIONS"
.SH NAME
getsigname \- choose a signal name in alias list 
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"
char \(**getsigname(ptsig)
losig_list \(**ptsig;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIptsig\fP
Pointer to \fBlosig_list\fP
.SH DESCRIPTION
The \fBgetsigname\fP function choose the higher hierachical level name of the
alias list of a signal.
The alias list is pointer to by the \fINAMECHAIN\fP pointer of the \fBlosig\fP
structure, and contains zero or more names corresponding to the signal.
Since the signal may result from a flatten, instance names may be concatenated
to the actual signal name.
.SH RETURN VALUE
\fBgetsigname\fP returns the higher hierachy level name, if
\fIptsig\->NAMECHAIN\fP is not \fBNULL\fP, else a name constructed with
the signal \fBINDEX\fP is returned.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"
void print_signame(p)
losig_list \(**p;
{
	fprintf(stdout, "signal name : %s\\n", getsigname(p));
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR losig (3),
.BR chain (3).


.so man1/alc_bug_report.1
