.\"   $Id: givelosig.3,v 1.1.1.1 2002/03/08 13:51:02 fred Exp $
.\" @(#)givelosig.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
givelosig
.XE
.XS3 \n%
.ti 0.2i
givelosig
.XE3 \}
.TH GIVELOSIG 3 "October 1, 1997" "ASIM/LIP6" "MBK LOGICAL UTILITY FUNCTIONS"
.SH NAME
givelosig \- give a logical signal
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"
losig_list \(**givelosig(ptfig, index)
lofig_list \(**ptfig;
long index;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIptfig\fP
Pointer to the figure in which the signal should be seeked or created
.TP
\fIindex\fP
Index of the signal to find or create
.SH DESCRIPTION
\fBgivelosig\fP looks in the list of signals of the logical model pointed
to by \fIptfig\fP for a signal identified by its \fIindex\fP. If this signal
exists, then its pointer is returned, else, the signal is created, with
direction, \fIDIR\fP, \fBUNKNOWN\fP, and \fITYPE\fP \fBINTERNAL\fP, and, of
course \fIINDEX\fP \fIindex\fP, and the pointer is returned.
.SH RETURN VALUE
\fBgivelosig\fP returns a pointer to the signal.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"
losig_list \(**give_sig_by_name(figname, index)
char \(**figname;
long index;
{
   /\(** never fails \(**/
   return givelosig(getlofig(figname), index);
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR lofig (3),
.BR losig (3),
.BR addlosig (3),
.BR dellosig (3).


.so man1/alc_bug_report.1

