.\"   $Id: guessextdir.3,v 1.1.1.1 2002/03/08 13:51:02 fred Exp $
.\" @(#)guessextdir.2 1.00 92/10/27 ; Labo masi cao-vlsi; Author : Vincent POUILLEY
.\"modified by Frederic Petrot to meet english language requirements!
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
guessextdir
.XE
.XS2 \n%
.ti 0.2i
guessextdir
.XE2 \}
.TH GUESSEXTDIR 3 "October 1, 1997" "ASIM/LIP6" "MBK LOGICAL UTILITY FUNCTIONS"
.SH NAME
guessextdir \- guess external connectors directions from internal connectors directions
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"
int guessextdir(ptfig)
lofig_list \(**ptfig;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIptfig\fP
Pointer to a lofig_list
.SH DESCRIPTION
The \fBguessextdir\fP function guesses external connectors directions from
internal connectors' ones.
The translation table below indicates the resulting direction
for two internals connectors.
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
         IN      OUT      INOUT  UNKNOWN  TRISTATE TRANSCV
IN       IN      INOUT    INOUT  IN       TRANSCV  TRANSCV
OUT      INOUT   OUT+     INOUT+ OUT      OUT+     TRANSCV+
INOUT    INOUT   INOUT+   INOUT+ INOUT    INOUT+   INOUT+
UNKNOWN  IN      OUT      INOUT  UNKNOWN  TRISTATE TRANSCV
TRISTATE TRANSCV OUT+     INOUT+ TRISTATE TRISTATE TRANSCV
TRANSCV  TRANSCV TRANSCV+ INOUT+ TRANSCV  TRANSCV  TRANSCV
.SH RETURN VALUE
\fBguessextdir\fP returns \fB1\fP on success, \fB0\fP
if there is an error in the translation.
.SH ERROR
The values followed by a \fB+\fP character in the translation table indicate
an error.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mut.h"
#include "mlo.h"
lofig_list \(** getgoodlofig(figname, mode)
char \(**figname;
char mode;
{
lofig_list \(**ptfig;
	ptfig = getlofig(figname, mode);
	restorealldir(ptfig);
	guessextdir(ptfig);
	return ptfig;
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR lofig (3),
.BR locon (3),
.BR getlofig (3),
.BR restorealldir (3).


.so man1/alc_bug_report.1

