.\"   $Id: incatalogfeed.3,v 1.1.1.1 2002/03/08 13:51:02 fred Exp $
.\" @(#)incatalogfeed.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
incatalogfeed
.XE
.XS4 \n%
.ti 0.2i
incatalogfeed
.XE4 \}
.TH INCATALOGFEED 3 "October 1, 1997" "ASIM/LIP6" "MBK UTILITY FUNCTIONS"
.SH NAME
incatalogfeed \- test if cell belongs to the catalog file
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mut.h"
int incatalogfeed(figname)
char \(**figname;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIfigname\fP
Name of the cell to be checked
.SH DESCRIPTION
\fBincatalogfeed\fP checks a cell represented by its \fIfigname\fP beeing
present in the catalog file with the \fI'F'\fP attribut.
This means that the cell is a feed through, and does not have a logical
equivalent representation while beeing physicaly used.
.br
This information is mostly needed by routers, since \fI"logical feed through"\fP
has no design meaning.
.br
The catalog is the sum of all the catalogs of the cells libraries specified
in the \fBMBK_CATA_LIB\fP(1) and \fBMBK_WORK_LIB\fP(1).
The catalogs of the \fBMBK_CATA_LIB\fP(1) are the files called \fBCATAL\fP,
and the \fBMBK_WORK_LIB\fP(1) is by default \fBCATAL\fP but can be changed
to \fBMBK_CATAL_NAME\fP(1).
.SH RETURN VALUE
\fBincatalogfeed\fP returns \fB0\fP if the cell does not belong to the
catalog with the \fB'F'\fP attribut, 
a value different from \fB0\fP if it does.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mut.h"
char \(**tell_if_incatalogfeed(name)
char \(**name;
{
	return incatalogfeed(name) ? "Jawohl, mein Herr" : "Nein, danke";
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR incatalog (3),
.BR incatalogdelete (3),
.BR incataloggds (3).


.so man1/alc_bug_report.1

