.\"   $Id: isck.3,v 1.2 2003/10/20 08:55:19 xtof Exp $
.\" @(#)isck.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
isck
.XE
.XS4 \n%
.ti 0.2i
isck
.XE4 \}
.TH ISCK 3 "October 1, 1997" "ASIM/LIP6" "MBK UTILITY FUNCTIONS"
.SH NAME
isck \-tells if a name is the pattern defined by the user
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mut.h"
int isck(s)
char \(**s;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIs\fP
Pointer to the string to be check as clock
.SH DESCRIPTION
\fBisck\fP compares the string defined by the \fBMBK_CK\fP(1)
environment variable with the string \fIs\fP.
If this string is not set by the user, its default value is "ck".
.SH RETURN VALUE
\fBisck\fP returns \fB0\fP the pattern is not present 
If the pattern is found, \fB1\fP is returned.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mut.h"
#include "mlo.h"
find_a_ck(f)
lofig_list *f;
{
locon_list *c;
losig_list *s;
	/* first check connectors */
	for (c = f->LOCON; c; c = c->NEXT) {
		if (isck(c->NAME))
			return c->SIG;
		if (isck(getsigname(c->SIG)))
			return c->SIG;
	}
	/* then check internal signals */
	for (s = f->LOSIG; s; s = s->NEXT)
		if (s->TYPE == INTERNAL)
			if (isck(getsigname(s)))
				return s;
	return NULL;
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR mbkenv (3),
.BR instr (3),
.BR isvdd (3),
.BR isvss (3),
.BR MBK_CK (1),
.BR MBK_VDD (1),
.BR MBK_VSS (1).


.so man1/alc_bug_report.1

