.\"   $Id: mbk.3,v 1.2 2002/07/30 10:27:02 xtof Exp $
.\" @(#)mbk.l 0.0 90/22/08 UPMC; Author: Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
\fBPresentation of generic \fIlayout\fP and \fInetlist\fP data structures\fR
.XE \}
.TH MBK 3 "October 1, 1997" "ASIM/LIP6" "cao\-vlsi reference manual"
.SH NAME
mbk \- Generic \fIlayout\fP ,\fInetlist\fP and \fIutility\fP data structures
.so man1/alc_origin.1
.SH DESCRIPTION
\fBmbk\fP has several global variables that need to be known by the programmer.

.SH SEE ALSO
.BR genlib (1).

.so man1/alc_bug_report.1

