.\"   $Id: mbkfree.3,v 1.1.1.1 2002/03/08 13:51:03 fred Exp $
.\" @(#)mbkfree.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
mbkfree
.XE
.XS4 \n%
.ti 0.2i
mbkfree
.XE4 \}
.TH MBKFREE 3 "October 1, 1997" "ASIM/LIP6" "MBK UTILITY FUNCTIONS"
.SH NAME
mbkfree \- mbk memory allocator
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mut.h"
void mbkfree(p)
void \(**p;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIp\fP
Pointer to be given back to the system
.SH DESCRIPTION
\fBmbkfree\fP frees a pointer.
It is now a day just an encapsulation of the system \fBfree\fP function,
but may evolve to a special allocator in the future. Its use is strongly
encouraged.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mut.h"
#include "mlo.h"
void free_con(pt)
lofig_list \(**pt;
{
locon_list \(**c = pt\->LOCON, \(**next;
	while (c) {
		next = c\->NEXT;
		mbkfree((void \(**)c);
		c = next;
	}
	pt\->LOCON = NULL;
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR mbkalloc (3).


.so man1/alc_bug_report.1

