.\"   $Id: savelofig.3,v 1.1.1.1 2002/03/08 13:51:04 fred Exp $
.\" @(#)savelofig.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
savelofig
.XE
.XS2 \n%
.ti 0.2i
savelofig
.XE2 \}
.TH SAVELOFIG 3 "October 1, 1997" "ASIM/LIP6" "MBK LOGICAL UTILITY FUNCTIONS"
.SH NAME
savelofig \- save a logical figure on disk 
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlu.h"
void savelofig(ptfig)
lofig_list \(**ptfig;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIptfig\fP
Pointer to the \fIlofig\fP to be written on disk
.SH DESCRIPTION
\fBsavelofig\fP writes on disk the contents of the figure pointer to by 
\fIptfig\fP. All the figure lists are ran through, and the appropriate objects
written, independently of the figure \fImode\fP. 
.br
The \fBsavelofig\fP function in fact performs a call to a driver, choosen
by the \fBMBK_OUT_LO\fP(1) environment variable. The directory in which the file
is to be written is the one set by \fBMBK_WORK_LIB\fP(1).
See \fBMBK_OUT_LO\fP(1), \fBMBK_WORK_LIB\fP(1) and
\fBmbkenv\fP(3) for details.
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"\(**\(**\(** mbk error \(**\(**\(** not supported logical output format 'xxx'"
.ft R
.RS
The environment variable \fIMBK_OUT_LO\fP is not set to a legal logical
format.
.RE
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"\(**\(**\(** mbk error \(**\(**\(** savelofig : could not open file \fIfigname.ext\fP"
.ft R
.RS
Either the directory or the file are write protected, so it's not possible to
open \fIfigname.ext\fP, where \fIext\fP is the file format extension, for 
writting.
.RE
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlu.h"
void save_na2_y()
{
	savelofig(getlofig("na2_y"));
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR mbkenv (3),
.BR lofig (3),
.BR addlofig (3),
.BR getlofig (3),
.BR dellofig (3),
.BR loadlofig (3),
.BR flattenlofig (3),
.BR rflattenlofig (3),
.BR MBK_OUT_LO (1),
.BR MBK_WORK_LIB (1).


.so man1/alc_bug_report.1

