.\"   $Id: upstr.3,v 1.1.1.1 2002/03/08 13:51:00 fred Exp $
.\" @(#)upstr.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
upstr
.XE
.XS4 \n%
.ti 0.2i
upstr
.XE4 \}
.TH UPSTR 3 "October 1, 1997" "ASIM/LIP6" "MBK UTILITY FUNCTIONS"
.SH NAME
upstr \- convert a string to upper case
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mut.h"
void upstr(s, t)
char \(**s, \(**t;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIs\fP
Pointer to the source string
.TP
\fIt\fP
Pointer to the destination string
.SH DESCRIPTION
\fBupstr\fP converts the \fIs\fP string to upper case in \fIt\fP.
The space for \fIt\fP must be allocated by the caller, and be at least
\fBstrlen(s) + 1\fP long.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mut.h"
void cmp()
{
char \(**s = "pwet", t[5];
	upstr(s, t);
	if (strcmp(t, "PWET")) {
		fprintf(stderr, "Upstr sucks, man");
		EXIT();
	}
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR downstr (3).


.so man1/alc_bug_report.1

