.\"   $Id: viewloins.3,v 1.1.1.1 2002/03/08 13:51:04 fred Exp $
.\" @(#)viewloins.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
viewloins
.XE
.XS2 \n%
.ti 0.2i
viewloins
.XE2 \}
.TH VIEWLOINS 3 "October 1, 1997" "ASIM/LIP6" "MBK LOGICAL FUNCTIONS"
.SH NAME
viewloins \- display elements of a \fBloins_list\fP
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"
void viewloins(pt)
loins_list \(**pt;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIpt\fP
Pointer to the \fBloins\fP to be scaned
.SH DESCRIPTION
\fBviewloins\fP scans all the primary elements of the \fBloins_list\fP 
pointed to by \fIpt\fP, and displays a textual output of the data strcuture
contents.
The \fILOCON\fP field is scaned, and its contents displayed.
.br
Its use is mostly for debugging purposes, and educational ones, since the
output is quite verbose, even if very easy to understand.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <stdio.h>
#include "mlo.h"
void view_ins(ptfig)
lofig_list \(**ptfig;
{
loins_list \(**ins;
	for (ins = ptfig\->LOINS; ins; ins = ins\->NEXT)
		viewloins(ins);
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR loins (3),
.BR viewlo (3),
.BR viewlofig (3),
.BR viewlotrs (3),
.BR viewlosig (3),
.BR viewloinscon (3),
.BR viewloinscon (3).


.so man1/alc_bug_report.1

