.\"   $Id: viewphfig.3,v 1.1.1.1 2002/03/08 13:51:04 fred Exp $
.\" @(#)viewphfig.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
viewphfig
.XE
.XS0 \n%
.ti 0.2i
viewphfig
.XE0 \}
.so man1/alc_origin.1
.SH NAME
viewphfig \- display elements of a \fBphfig_list\fP
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mph.h"
void viewphfig(ptfig)
phfig_list \(**ptfig;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIptfig\fP
Pointer to the \fBphfig\fP to be scaned
.SH DESCRIPTION
\fBviewphfig\fP scans all the primary elements of the \fBphfig_list\fP 
loaded in ram, and displays a textual output of the data strcuture contents.
The \fIPHINS\fP, \fIPHCON\fP, \fIPHSEG\fP, \fIPHVIA\fP and \fIPHREF\fP are
scaned, and their contents displayed.
.br
Its use is mostly for debugging purposes, and educational ones, since the
output is quite verbose, if very easy to understand.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <stdio.h>
#include "mph.h"
void view_fig_to_file(ptfig)
phfig_list \(**ptfig;
{
FILE \(**file = freopen(ptfig\->NAME, WRITE_TEXT, stdout);
	if (!file) {
		(void)fputs("Can't reopen stdout!\\n", stderr);
		EXIT();
	}
	viewphfig(ptfig); /\(** to file called name \(**/
	(void)fclose(file);
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR phfig (3),
.BR viewph (3),
.BR viewphins (3),
.BR viewphseg (3),
.BR viewphref (3),
.BR viewphvia (3),
.BR viewphcon (3).


.so man1/alc_bug_report.1

