.\"   $Id: viewlo.3,v 1.1.1.1 2002/03/08 13:51:04 fred Exp $
.\" @(#)viewlo.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
viewlo
.XE
.XS2 \n%
.ti 0.2i
viewlo
.XE2 \}
.TH VIEWLO 3 "October 1, 1997" "ASIM/LIP6" "MBK LOGICAL FUNCTIONS"
.SH NAME
viewlo \- scan all \fBlofig_list\fPs and display their elements
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"
void viewlo();
.ft R
.fi
.SH DESCRIPTION
\fBviewlo\fP scans all the elements of the entire \fBlofig_list\fP 
loaded in ram, and displays a textual output of the data strcuture contents.
All the figures are treated, the first one beeing pointed to by
\fBHEAD_LOFIG\fP, the global variable that points to the head of all
\fBlofig\fPs.
.br
Its use is mostly for debugging purposes, and educational ones, since the
output is quite verbose, if very easy to understand.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <stdio.h>
#include "mlo.h"
void view_all_to_file(name)
char \(**name;
{
FILE \(**file = freopen(name, WRITE_TEXT, stdout);
	if (!file) {
		(void)fputs("Can't reopen stdout!\\n", stderr);
		EXIT();
	}
	viewlo(); /\(** to file called name \(**/
	(void)fclose(file);
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR lofig (3),
.BR viewlofig (3),
.BR viewloins (3),
.BR viewlotrs (3),
.BR viewlosig (3),
.BR viewloinscon (3),
.BR viewlofigcon (3).


.so man1/alc_bug_report.1

