.\"   $Id: viewlofigcon.3,v 1.1.1.1 2002/03/08 13:51:04 fred Exp $
.\" @(#)viewlofigcon.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
viewlofigcon
.XE
.XS2 \n%
.ti 0.2i
viewlofigcon
.XE2 \}
.so man1/alc_origin.1
.SH NAME
viewlofigcon \- display elements of a \fBlocon_list\fP attached to a
figure
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"
void viewlofigcon(ptcon)
locon_list \(**ptcon;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIptcon\fP
Pointer to the \fBlocon\fP to be scaned
.SH DESCRIPTION
\fBviewlofigcon\fP scans all the primary elements of the \fBlocon_list\fP 
loaded in ram, and displays a textual output of the data strcuture contents.
.br
Its use is mostly for debugging purposes, and educational ones, since the
output is quite verbose, even if very easy to understand.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <stdio.h>
#include "mlo.h"
void view_figcon(ptfig)
lofig_list \(**ptfig;
{
locon_list \(**figcon;
	for (figcon = ptfig\->LOCON; figcon; figcon = figcon\->NEXT)
		viewlofigcon(figcon);
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR locon (3),
.BR lofig (3),
.BR viewlo (3),
.BR viewlofig (3),
.BR viewlotrs (3),
.BR viewlosig (3),
.BR viewloinscon (3),
.BR viewlofigcon (3).


.so man1/alc_bug_report.1

