.\"   $Id: viewphcon.3,v 1.1.1.1 2002/03/08 13:51:04 fred Exp $
.\" @(#)viewphcon.2 2.11 91/08/22 ; Labo masi cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
viewphcon
.XE
.XS0 \n%
.ti 0.2i
viewphcon
.XE0 \}
.TH VIEWPHCON 3 "October 1, 1997" "ASIM/LIP6" "MBK PHYSICAL FUNCTIONS"
.SH NAME
viewphcon \- display elements of a \fBphcon_list\fP
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mph.h"
void viewphcon(pt)
phcon_list \(**pt;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIpt\fP
Pointer to the \fBphcon\fP to be scaned
.SH DESCRIPTION
\fBviewphcon\fP scans all the primary elements of the \fBphcon_list\fP 
pointed to by \fIpt\fP, and displays a textual output of the data strcuture
contents.
.br
Its use is mostly for debugging purposes, and educational ones, since the
output is quite verbose, even if very easy to understand.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <stdio.h>
#include "mph.h"
void view_con(ptfig)
phfig_list \(**ptfig;
{
phcon_list \(**con;
	for (con = ptfig\->PHCON; con; con = con\->NEXT)
		viewphcon(con);
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR phcon (3),
.BR viewph (3),
.BR viewphfig (3),
.BR viewphseg (3),
.BR viewphref (3),
.BR viewphvia (3),
.BR viewphins (3).


.so man1/alc_bug_report.1

