.\"   $Id: GENLIB_DEF_AB.3,v 1.1.1.1 2002/03/08 14:08:09 fred Exp $
.\" @(#)GENLIB_DEF_AB.3 2.11 91/08/22; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
GENLIB_DEF_AB
.XE \}
.TH GENLIB_DEF_AB.3 "October 1, 1997" "ASIM/LIP6" "PROCEDURAL GENERATION LANGUAGE"
.SH NAME
GENLIB_DEF_AB \- define a new \fIabutment box\fP to the current layout cell
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
void GENLIB_DEF_AB(dx1, dy1, dx2, dy2);
long dx1, dy1, dx2, dy2;
.ft R
.fi
.so man1/alc_origin.1
.SH PARAMETERS
.TP 20
\fIdx1, dy1\fP
Values to be added to the lower left corner of the previous \fIabutment box\fP
.TP
\fIdx2, dy2\fP
Values to be added to the upper right corner of the previous \fIabutment box\fP
.SH DESCRIPTION
\fBDEF_AB\fP give a new \fIabutment box\fP to the current physical cell.
The coordinates of
the \fIabutment box\fP are the coordinates of the envelop of the \fIabutment boxes\fP of
each instance plus the delta values given as argument. The \fI(dx1, dy1)\fP
values are added to the (x1, y1) coordinates of the bottom left corner of the
\fI"standard abutment box"\fP (the envelop), and the \fI(dx2, dy2)\fP
are added to the top right ones.
You have to call this function before saving, otherwise the figure will not
have an \fIabutment box\fP. Since it's regarding the \fIabutment box\fP
of its model that an instance is placed, any futher use of this figure
will be incorrect if \fBDEF_AB\fP isn't called, or properly defined.
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"GENLIB_DEF_AB impossible : missing GENLIB_DEF_PHFIG"
.ft R
.RS
No figure has been yet specified by a call to \fBDEF_PHFIG\fP. So it isn't
possible to give it a size.
you must call \fBDEF_PHFIG\fP before any other layout action.
.RE
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
main()
{
	/\(** Create a figure to work on  \(**/
	GENLIB_DEF_PHFIG("cell");
	/\(** Place an instance \(**/
	GENLIB_PLACE("model","i1", NOSYM,0L,0L);
	GENLIB_PLACE("model","i2", NOSYM,120L,40L);
	GENLIB_DEF_PHINS("i1");
	GENLIB_PLACE_TOP("model2", "i3", NOSYM);
	/\(** define the new abutment box as the standard envelop \(**/
	GENLIB_DEF_AB(0, 0, 0, 0);
	/\(** Save all that on disk \(**/
	GENLIB_SAVE_PHFIG();
}
.ft R
.fi
.SH SEE ALSO
.BR genlib (1),
.BR GENLIB_SAVE_PHFIG (3).


.so man1/alc_bug_report.1

