.\"   $Id: GENLIB_LOAD_PHFIG.3,v 1.1.1.1 2002/03/08 14:08:10 fred Exp $
.\" @(#)GENLIB_LOAD_PHFIG.3 2.11 91/08/22 ; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
GENLIB_LOAD_PHFIG
.XE \}
.TH GENLIB_LOAD_PHFIG.3 "October 1, 1997" "ASIM/LIP6" "PROCEDURAL GENERATION LANGUAGE"
.SH NAME
\fBPHAD_PHFIG\fP \- loads a layout form disk and opens it as current figure
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
void GENLIB_LOAD_PHFIG(cellname)
char \(**cellname;
.ft R
.fi
.so man1/alc_origin.1
.SH PARAMETERS
.TP 20
\fIcellname\fP
Name of the cell which all futher calls to genlib layout functions will
work on 
.SH DESCRIPTION
\fBPHAD_PHFIG\fP loads a physical view from disk and defines it as current
working layout figure. 
This overrides the working figure initialized by \fBDEF_PHFIG\fP(3), if any.
So the next call to \fBSAVE_PHFIG\fP will save the cell called \fIcellname\fP.
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
main()
{
	/\(** Loads the figure to work on  \(**/
	GENLIB_LOAD_PHFIG("cell");
	/\(** Add an instance in cell \(**/
	GENLIB_PLACE("model","instance", NOSYM, 200, 600);
	/\(** Save all that on disk \(**/
	GENLIB_SAVE_PHFIG();
}
.ft R
.fi
.SH SEE ALSO
.BR genlib (1),
.BR GENLIB_DEF_PHFIG (3).
.BR GENLIB_SAVE_PHFIG (3).


.so man1/alc_bug_report.1

