.\"   $Id: GENLIB_GET_INS_Y.3,v 1.1.1.1 2002/03/08 14:08:10 fred Exp $
.\" @(#)GENLIB_GET_INS_Y.3 2.11 01/92; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
GENLIB_GET_INS_Y
.XE \}
.TH GENLIB_GET_INS_Y.3 "October 1, 1997" "ASIM/LIP6" "PROCEDURAL GENERATION LANGUAGE"
.SH NAME
GENLIB_GET_INS_Y \- retrieve the y coordinate of an instance
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
long GENLIB_GET_INS_Y(insname)
char \(**insname;
.ft R
.fi
.so man1/alc_origin.1
.SH PARAMETER
.TP 20
\fIinsname\fP
Name of the instance which y coordinate is to be given back
.SH DESCRIPTION
\fBGET_INS_Y\fP looks for 
the instance called \fIinsname\fP in the current figure.
Then it computes its absolute coordinates in the figure, and gives back its
y coordinate.
.SH RETURN VALUE
The function returns a long int beeing the y position of the instance
in the current figure
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"GENLIB_GET_INS_Y impossible : missing GENLIB_DEF_PHFIG"
.ft R
.RS
No figure has been yet specified by a call to \fBDEF_PHFIG\fP. So it isn't
possible to place a connector inside it.
you must call \fBDEF_PHFIG\fP before any other layout action.
.RE
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"illegal getphins : instance called \fIinsname\fP does not exist"
.ft R
.RS
No instance called \fIinsname\fP exists in the current figure.
.RE
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
main()
{
long x, y;
	/\(** Create a figure to work on  \(**/
	GENLIB_DEF_PHFIG("cell");
	GENLIB_PLACE("gaci0_b", "r1", NOSYM, 23L, 54L);
	GENLIB_PLACE_TOP("gaci0_b", "r2", SYM_Y);
	GENLIB_PLACE_RIGHT("gaci0_b", "r3", SYM_Y);
	/\(** Get a connector \(**/
	x = GENLIB_GET_INS_X("r3");
	y = GENLIB_GET_INS_Y("r3");
	.
	.
	/\(** Save that on disk \(**/
	GENLIB_SAVE_PHFIG();
}
.ft R
.fi
.SH SEE ALSO
.BR genlib (1),
.BR GENLIB_DEF_PHFIG (3),
.BR GENLIB_SAVE_PHFIG (3),
.BR PHINS (3),
.BR GENLIB_GET_INS_X (3),
.BR GENLIB_GET_CON_X (3),
.BR GENLIB_GET_CON_Y (3).
.BR GENLIB_GET_REF_X (3),
.BR GENLIB_GET_REF_Y (3).


.so man1/alc_bug_report.1

