.\"   $Id: GENLIB_SAVE_PHSC.3,v 1.1.1.1 2002/03/08 14:08:11 fred Exp $
.\" @(#)GENLIB_SAVE_PHSC.3 2.11 91/08/22; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
GENLIB_SAVE_PHSC
.XE \}
.TH GENLIB_SAVE_PHSC.3 "October 1, 1997" "ASIM/LIP6" "PROCEDURAL GENERATION LANGUAGE"
.SH NAME
GENLIB_SAVE_PHSC \- save a layout on disk
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
void GENLIB_SAVE_PHSC();
.ft R
.fi
.so man1/alc_origin.1
.SH DESCRIPTION
\fBSAVE_PHSC\fP saves the current working figure previously definded by
a \fBDEF_PHFIG\fP or \fBDEF_PHSC\fP call, and performs a
\fBDEF_AB(0L, 0L, 0L, 0L)\fP just before saving the figure, in order to give
it the appropriate size for standard cell blocks.
\fBSAVE_PHSC\fP uses environment variables to choose the file format and 
the path to the file.
.br
No check is made to see if a file with the same name already exists on disk, so
be careful not to overwrite some precious data.
.SH ERROR
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"GENLIB_SAVE_PHSC impossible : missing GENLIB_DEF_PHFIG"
.ft R
.RS
No figure has been yet specified by a call to \fBDEF_PHFIG\fP or
\fBDEF_PHSC\fB. So it isn't
possible to save anything. you must call \fBDEF_PHFIG\fP before any other
layout action.
.RE
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
main()
{
	/\(** Create a physical figure to work on \(**/
	GENLIB_DEF_PHSC("cell");
	/\(** Place an instance \(**/
	GENLIB_SC_PLACE("finst", NOSYM,0L,0L);
	/\(** Save all that on disk \(**/
	GENLIB_SAVE_PHSC();
}
.ft R
.fi
.SH SEE ALSO
.BR genlib (1),
.BR GENLIB_DEF_PHSC (3),
.BR MBK_OUT_PH (1),
.BR MBK_WORK_LIB (1).


.so man1/alc_bug_report.1

