.\"   $Id: GENLIB_PHVIA.3,v 1.1.1.1 2002/03/08 14:08:10 fred Exp $
.\" @(#)GENLIB_PHVIA.3 2.11 91/08/22 ; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
GENLIB_PHVIA
.XE \}
.TH GENLIB_PHVIA.3 "October 1, 1997" "ASIM/LIP6" "PROCEDURAL GENERATION LANGUAGE"
.SH NAME
GENLIB_PHVIA \- place a physical via in the current figure at absolute coordinates
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
void GENLIB_PHVIA(type, x, y)
char type;
long x, y;
.ft R
.fi
.so man1/alc_origin.1
.SH PARAMETERS
.TP 20
\fItype\fP
Type of the contact to be made
.TP
\fIx, y\fP
Absolute coordinates of the via
.SH DESCRIPTION
\fBPHVIA\fP adds a via in the current layout cell, at the specified
coordinates.
The \fItype\fP argument may take the following legal values:
.TP 20
\fBCONT_POLY\fP 
links \fBPOLY\fP and \fBALU1\fP
.TP
\fBCONT_DIF_N\fP 
links \fBNDIF\fP and \fBALU1\fP
.TP
\fBCONT_DIF_P\fP 
links \fBPDIF\fP and \fBALU1\fP
.TP
\fBCONT_BODY_N\fP 
links \fBNTIE\fP and \fBALU1\fP
.TP
\fBCONT_BODY_P\fP 
links \fBPTIE\fP and \fBALU1\fP
.TP
\fBCONT_VIA\fP 
links \fBALU1\fP and \fBALU2\fP
.TP
\fBCONT_VIA2\fP 
links \fBALU2\fP and \fBALU3\fP
.TP
\fBC_X_N\fP 
corner for L-shaped (and S-shaped) N transistor
.TP
\fBC_X_P\fP 
corner for L-shaped (and S-shaped) P transistor
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"GENLIB_PHVIA impossible : missing GENLIB_DEF_PHFIG"
.ft R
.RS
No figure has been yet specified by a call to \fBDEF_PHFIG\fP. So it isn't
possible to place a via inside it.
you must call \fBDEF_PHFIG\fP before any other layout action.
.RE
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"illegal addphvia : type is XX  at \fIx, y\fP"
.ft R
.RS
The \fItype\fP parameter does not have a legal value, but \fIXX\fP.
.RE
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
main()
{
	/\(** Create a figure to work on  \(**/
	GENLIB_DEF_PHFIG("cell");
	.
	/\(** Put a via \(**/
	GENLIB_PHVIA(CONT_VIA, 12L, 10L);
	.
	.
	GENLIB_DEF_AB(0L, 0L, 0L, 0L);
	/\(** Save that on disk \(**/
	GENLIB_SAVE_PHFIG();
}
.ft R
.fi
.SH SEE ALSO
.BR genlib (1),
.BR GENLIB_DEF_PHFIG (3),
.BR GENLIB_SAVE_PHFIG (3),
.BR GENLIB_PLACE_VIA_REF (3).


.so man1/alc_bug_report.1

