.\"   $Id: GENLIB_SET_LOSELF.3,v 1.1 2002/08/16 19:15:02 pnt Exp $
.\" @(#)GENLIB_SET_LOSELF.2 2.11 2002/08/14 ; Labo LIP6/ASIM cao-vlsi; Author : Pierre Nguyen Tuong
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
GENLIB_SET_LOSELF
.XE
.XS2 \n%
.ti 0.2i
GENLIB_SET_LOSELF
.XE2 \}
.TH GENLIB_SET_LOSELF 3 "August 14, 2002" "ASIM/LIP6" "MBK LOGICAL FUNCTIONS"
.SH NAME
GENLIB_SET_LOSELF \- set the inductance value of a logical inductor, after its creation.
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "mlo.h"

void GENLIB_SET_LOSELF(figname,selfname,newself)
char \(**figname ;
char \(**selfname ;
double newself ;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIfigname\fP
Name of the logical figure
.TP
\fIselfname\fP
Instance name of the inductor
.TP
\fInewself\fP
New inductance value
.SH DESCRIPTION
\fBGENLIB_SET_LOSELF\fP looks in the list of inductors of the logical model \fIfigname\fP
for a inductor identified by its instance \fIselfname\fP and set
the SELF field to the newself value.
.SH RETURN VALUE
None
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"\(**\(**\(** mbk error \(**\(**\(** getloself impossible :
inductor \fIname\fP doesn't exist in figure \fIptfig \-> NAME\fP"
.ft R
.RS
No inductor matches the name. 
.RE
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>

int main(int argc,char \(**argv[])
{
  /\(** Create a figure to work on, a parallel inductor \(**/
  GENLIB_DEF_LOFIG("parallel_self") ;

  /\(** Define interface \(**/
  GENLIB_LOCON("i",IN,"input") ;
  GENLIB_LOCON("f",OUT,"output") ;

  /\(** Add inductors \(**/
  GENLIB_LOSELF(SELFMIM,5.1,"input","output","self1") ;
  GENLIB_LOSELF(SELFMIM,5.2,"input","output","self2") ;

  /* Modify inductors value */
  GENLIB_SET_LOSELF("parallel_self","self1",6.2) ;
  GENLIB_SET_LOSELF("parallel_self","self2",6.3) ;

  /\(** Save all that on disk \(**/
  GENLIB_SAVE_LOFIG() ;

  return 0 ;
}
.ft R
.fi
.SH SEE ALSO
.BR mbk (1),
.BR GENLIB_DEF_LOFIG (3),
.BR GENLIB_LOSELF(3)


.so man1/alc_bug_report.1

