.\"   $Id: GENLIB_PHSEG.3,v 1.1.1.1 2002/03/08 14:08:10 fred Exp $
.\" @(#)GENLIB_PHSEG.3 2.11 91/08/22 ; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
GENLIB_PHSEG
.XE \}
.TH GENLIB_PHSEG.3 "October 1, 1997" "ASIM/LIP6" "PROCEDURAL GENERATION LANGUAGE"
.SH NAME
GENLIB_PHSEG \- place a physical segment in the current figure at absolute coordinates
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
void GENLIB_PHSEG(layer, width, name, x1, y1, x2, y2)
char layer;
long width;
char \(**name;
long x1, y1, x2, y2;
.ft R
.fi
.so man1/alc_origin.1
.SH PARAMETERS
.TP 20
\fIlayer\fP
Layout layer of the segment
.TP
\fIwidth\fP
Width of the segment
.TP
\fIname\fP
Name to be given to the segment
.TP
\fIx1, y1, x2, y2\fP
Coordinates of the segment's end points in the current figure
.SH DESCRIPTION
\fBPHSEG\fP adds a segment in the current layout cell, at the specified
coordinates, with the given attributs.
The \fIlayer\fP argument can take the following legal values :
.RS
.TP
\fBNWELL\fP 
.TP
\fBPWELL\fP 
.TP
\fBNTIE\fP 
.TP
\fBPTIE\fP 
.TP
\fBNDIF\fP 
.TP
\fBPDIF\fP 
.TP
\fBNTRANS\fP 
.TP
\fBPTRANS\fP 
.TP
\fBPOLY\fP 
.TP
\fBALU1\fP 
.TP
\fBALU2\fP 
.TP
\fBALU3\fP 
.TP
\fBTPOLY\fP 
.TP
\fBTALU1\fP 
.TP
\fBTALU2\fP 
.TP
\fBTALU3\fP 
.RE
.LP
The name argument needs not to be specified, since one usually doesn't need to
give a segment a name. To do so, just type "" as name.
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"GENLIB_PHSEG impossible : missing GENLIB_DEF_PHFIG"
.ft R
.RS
No figure has been yet specified by a call to \fBDEF_PHFIG\fP. So it isn't
possible to place an instance inside it.
you must call \fBDEF_PHFIG\fP before any other layout action.
.RE
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"illegal addphseg : x1, y1, x2, y2"
.ft R
.RS
A symbolic segment must be either vertical or horizontal, so either
\fIx1 = x2\fP, or \fIy1 = y2\fP.
.RE
.br
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
main()
{
	/\(** Create a figure to work on  \(**/
	GENLIB_DEF_PHFIG("cell");
	/\(** Put a segment \(**/
	GENLIB_PHSEG(ALU1, 1, "", 0L, 0L, 12L, 0L);
	/\(** Save that on disk \(**/
	GENLIB_SAVE_PHFIG();
}
.ft R
.fi
.SH SEE ALSO
.BR genlib (1),
.BR GENLIB_DEF_PHFIG (3),
.BR GENLIB_SAVE_PHFIG (3),
.BR GENLIB_COPY_UP_SEG (3),
.BR GENLIB_THRU_H (3),
.BR GENLIB_THRU_CON_H (3),
.BR GENLIB_THRU_V (3),
.BR GENLIB_THRU_CON_V (3),
.BR GENLIB_WIRE1 (3),
.BR GENLIB_WIRE2 (3),
.BR GENLIB_WIRE3 (3).


.so man1/alc_bug_report.1

