.\"   $Id: GENLIB_SAVE_PHFIG.3,v 1.1.1.1 2002/03/08 14:08:11 fred Exp $
.\" @(#)GENLIB_SAVE_PHFIG.3 2.11 91/08/22; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
GENLIB_SAVE_PHFIG
.XE \}
.TH GENLIB_SAVE_PHFIG.3 "October 1, 1997" "ASIM/LIP6" "PROCEDURAL GENERATION LANGUAGE"
.SH NAME
GENLIB_SAVE_PHFIG \- save a layout on disk
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
void GENLIB_SAVE_PHFIG();
.ft R
.fi
.so man1/alc_origin.1
.SH DESCRIPTION
\fBSAVE_PHFIG\fP saves the current working figure previously definded by
a \fBDEF_PHFIG\fP call. \fBSAVE_PHFIG\fP uses environment variables to
choose the file format and the path to the file.
.br
\fBMBK_OUT_PH\fP set up the output file format, the valid ones beeing :
.RS
\fBcp
.br
ap\fP
.RE
you could for example do :
.RS
\fBsetenv MBK_OUT_PH ap\fP
.RE
\fBMBK_WORK_LIB\fP set up the output file path. Any valid unix path is
ok.
.br
for example :
.RS
	\fBsetenv MBK_WORK_LIB ~fred/booth/genlib\fP
.RE
\fBSAVE_PHFIG\fP doesn't look on disk for the figure \fIcellname\fP, 
so be careful not to overwrite an existing file while saving.
.SH ERROR
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"GENLIB_SAVE_PHFIG impossible : missing GENLIB_DEF_PHFIG"
.ft R
.RS
No figure has been yet specified by a call to \fBDEF_PHFIG\fP. So it isn't
possible to save anything. you must call \fBDEF_PHFIG\fP before any other
layout action.
.RE
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
main()
{
	/\(** Create a figure to work on  \(**/
	GENLIB_DEF_PHFIG("mycell");
	/\(** Place an instance \(**/
	GENLIB_PLACE("mymodel","firstinstance", NOSYM,0L,0L);
	/\(** Save all that on disk \(**/
	GENLIB_SAVE_PHFIG();
}
.ft R
.fi
.SH SEE ALSO
.BR genlib (1),
.BR GENLIB_SAVE_PHSC (3),
.BR MBK_OUT_PH (1),
.BR MBK_WORK_LIB (1).


.so man1/alc_bug_report.1

