.\"   $Id: GENLIB_REVERSE_PHCON.3,v 1.1.1.1 2002/03/08 14:08:11 fred Exp $
.\" @(#)GENLIB_REVERSE_PHCON.3 2.11 93/09/03 ; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
GENLIB_REVERSE_PHCON
.XE \}
.TH GENLIB_REVERSE_PHCON.3 "October 1, 1997" "ASIM/LIP6" "PROCEDURAL GENERATION LANGUAGE"
.SH NAME
GENLIB_REVERSE_PHCON \- reverse the order of physical connectors on a bus.
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
void GENLIB_REVERSE_PHCON(basename)
char \(**basename;
.ft R
.fi
.so man1/alc_origin.1
.SH PARAMETERS
.TP 20
\fIbasename\fP
Radical of the vector to be reversed.
.SH DESCRIPTION
\fBREVERSE_PHCON\fP will change the indexes of the vector called
\fIbasename\fP, making the greatest values the smallest and so on.
Both hard connectors, created by \fBPHCON\fR(3) like functions and
virtual ones, done with \fBPHREF\fR(3), will be taken into account for
the reverse operation.
This function is mainly useful to implement the \fBmsb0\fR options of
the \fBAlliance\fR CAD system module generators, as the whole design can
be done with the designer choosen bit ordering, and modified on user
demand only before saving.
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
main()
{
	GENLIB_DEF_PHFIG("rom");
	/\(** Create a figure to work on  \(**/
	.
	.
	.
	/\(** Reverse the bit ordering if needed \(**/
	if (msb0)
		GENLIB_REVERSE_PHCON("adr");
	/\(** Save all that on disk \(**/
	GENLIB_SAVE_PHFIG();
}
.ft R
.fi
.SH SEE ALSO
.BR genlib (1),
.BR GENLIB_PHCON (3),
.BR GENLIB_PHREF (3),
.BR GENLIB_COPY_UP_CON (3),
.BR GENLIB_COPY_UP_ALL_CON (3),
.BR GENLIB_COPY_UP_CON_FACE (3),
.BR GENLIB_COPY_UP_REF (3).


.so man1/alc_bug_report.1

