.\"   $Id: GENLIB_DEF_LOFIG.3,v 1.1.1.1 2002/03/08 14:08:10 fred Exp $
.\" @(#)GENLIB_DEF_LOFIG.3 2.11 91/08/22 ; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
GENLIB_DEF_LOFIG
.XE \}
.TH GENLIB_DEF_LOFIG.3 "October 1, 1997" "ASIM/LIP6" "PROCEDURAL GENERATION LANGUAGE"
.SH NAME
GENLIB_DEF_LOFIG \- open a netlist model as current figure
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
void GENLIB_DEF_LOFIG(cellname)
char \(**cellname;
.ft R
.fi
.so man1/alc_origin.1
.SH PARAMETERS
.TP 20
\fIcellname\fP
Name of the cell which all futher calls to genlib logical functions will work on 
.SH DESCRIPTION
\fBDEF_LOFIG\fP defines the current working structural figure by it's name, 
the \fIcellname\fP argument. It can be use anywhere in the \fBgenlib\fP 
program, but must appear at least once at the top of it, since it also 
initalize the user's preferences through environment variables.
.br
If the figure called cellname doesn't exists in memory, it is created. 
If it already exists in memory, it makes it the current working figure. 
\fBDEF_LOFIG\fP doesn't look on disk for the figure \fIcellname\fP, 
so be careful not to overwrite an existing file while saving later on.
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
main()
{
	/\(** Create a figure to work on  \(**/
	GENLIB_DEF_LOFIG("cell");
	/\(** Place an instance \(**/
	GENLIB_LOINS("model","instance", "sig1", "sig2", "sig3", "vdd", "vss", EOL);
	/\(** Save all that on disk \(**/
	GENLIB_SAVE_LOFIG();
}
.ft R
.fi
.SH SEE ALSO
.BR genlib (1),
.BR GENLIB_SAVE_LOFIG (3).


.so man1/alc_bug_report.1

