.\"   $Id: GENLIB_LOTRS.3,v 1.2 2002/08/16 13:46:32 pnt Exp $
.\" @(#)GENLIB_LOTRS.3 2.11 91/08/22; Labo Cao-vlsi; Author : Frederic Petrot
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
GENLIB_LOTRS
.XE \}
.TH GENLIB_LOTRS.3 "October 1, 1997" "ASIM/LIP6" "PROCEDURAL GENERATION LANGUAGE"
.SH NAME
GENLIB_LOTRS \- adds a logical transistor to the current netlist figure
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
void GENLIB_LOTRS(type,width,length,grid,source,drain)
char type;
long width, length;
char \(**grid, \(**source, \(**drain;
.ft R
.fi
.so man1/alc_origin.1
.SH PARAMETERS
.TP 20
\fItype\fP
Type of the transistor to be created in the current figure
.TP
\fIwidth, length\fP
Size of the transistor
.TP
\fIgrid, source, drain\fP
Name of the signals on which the given transistor connector are to be linked
.SH DESCRIPTION
\fBLOTRS\fP add a logical transistor to the current
working figure. This transistor has each of its pin logicaly linked to the
adequat signal given as parameter.
The \fItype\fP attribut may take the following values:
.TP
\fBTRANSN\fP
for a N type mos transistor.
.TP
\fBTRANSP\fP 
for a P type mos transistor.
.SH ERROR
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"GENLIB_LOTRS impossible : missing GENLIB_DEF_LOFIG"
.ft R
.RS
No figure has been yet specified by a call to \fBDEF_LOFIG\fP. So it isn't
possible to add anything. you must call \fBDEF_LOFIG\fP before any other
netlist call.
.RE
.SH EXAMPLE
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include <genlib.h>
main()
{
	/\(** Create a figure to work on, an inverter  \(**/
	GENLIB_DEF_LOFIG("n1");
	/\(** define interface  \(**/
	GENLIB_LOCON("i", IN, "input");
	GENLIB_LOCON("f", OUT, "output");
	GENLIB_LOCON("vdd", IN, "vdd");
	GENLIB_LOCON("vss", IN, "vss");
	/\(** Place transistors \(**/
	GENLIB_LOTRS(TRANSP, 5, 4, "input", "vdd", "output");
	GENLIB_LOTRS(TRANSN, 2, 4, "input", "vss", "output");
	/\(** Save all that on disk \(**/
	GENLIB_SAVE_LOFIG();
}
.ft R
.fi
.SH SEE ALSO
.BR genlib (1),
.BR GENLIB_BUS (3),
.BR GENLIB_ELM (3),
.BR GENLIB_LOINS (3),
.BR GENLIB_LOCON (3).


.so man1/alc_bug_report.1

