.\"   $Id: log.1,v 1.2 2002/10/02 14:09:09 xtof Exp $
.\" @(#)log.l 0.0 92/08/01 UPMC; Author: Luc Burgun
.pl -.4
.TH LOG 1 "October 1, 1997" "ASIM/LIP6" "cao\-vlsi reference manual"
.SH NAME
\fBlog\fP \- logical representations for boolean functions and utilities.
.so man1/alc_origin.1
.SH DESCRIPTION
\fBlog\fP is a set of structures and functions that permits to manipulate several representations of boolean functions. Several programs and libraries of the \fIcao-vlsi cad tools\fP rest on the \fIlog\fP package. Three different kind of functions are available for:
.TP 20
Hash table management
.TP 20
Prefixed representation for boolean functions
.TP 20
Ordered binary decision diagrams representation
.SH EXAMPLE
Let's suppose that actual mbk version is 'nnn'.
In order to use log, \fIlibMutnnn.a\fP library must be called. 
.br
\fImakefile\fP:
.br
HEADER = -I/labo/include 
.br
LIB = -L/labo/lib -lMut -ltsh -labl -lbdd
.br
Each library can be called separatly. The "log.h" header file must be inserted in the files that use the functions or the structures defined in a library.  
.br
.SH SEE ALSO
.BR mbk (1),
.BR beh (1),
.SH AUTHOR
L. BURGUN salle 30 T. 55-65 Universite P&M Curie - 4 pl. Jussieu - FRANCE
.br
.SH THANKS
Thanks to P. REMY, F. PETROT, P. ALLEGRE and N. DICTUS.

.so man1/alc_bug_report.1

