.\"   $Id: createNodeTermBdd.3,v 1.1.1.1 2002/04/03 13:13:26 ludo Exp $
.\" @(#)createNodeTermBdd.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH CREATENODETERMBDD 3 "October 1, 1997" "ASIM/LIP6" "BDD functions"
.so man1/alc_origin.1
.SH NAME
\fBcreateNodeTermBdd\fP \- creates a terminal node of variable.
.SH SYNOPSYS
.nf
#include "logmmm.h"
pNode createNodeTermBdd(index)
short index;
.fi
.SH PARAMETER
.TP 20
\fIindex\fP
associated index 
.SH DESCRIPTION
\fBcreateNodeTermBdd()\fP creates a terminal node corresponding to \fIindex\fP. Because of reduction table, this function always returns the same \fIpNode\fP for a given \fIindex\fP. 0 and 1 \fIindex\fP are reserved to the \fIzero\fP and \fIone\fP nodes.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
pNode nodeA;

initializeBdd(SMALL_BDD);
nodeA = createNodeTermBdd(3);
displayBdd(nodeA,1);

/* it will display 
@nodeA   INDEX = 2   LOW = ZERO   HIGH = ONE
*/
nodeA = createNodeTermBdd(3);	/* nodeA doesn't change */
	
destroyBdd(1);
.fi
.SH ERROR
"createNodeTermBdd : error - index < 2"
.br
\fIindex\fP must be strictly higher than 1.
.SH SEE ALSO
.BR log (1),
.BR bdd (1),
.BR applyBinBdd (3),
.BR applyBdd (3),
.BR addListBdd (3),
.BR displayBdd (3),
.BR notBdd (3).

.so man1/alc_bug_report.1

