.\"   $Id: markAllBdd.3,v 1.1.1.1 2002/04/03 13:13:26 ludo Exp $
.\" @(#)markAllBdd.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH MARKALLBDD 3 "October 1, 1997" "ASIM/LIP6" "BDD functions"
.so man1/alc_origin.1
.SH NAME
\fBmarkAllBdd\fP \- marks all the nodes of the BDDs system
.SH SYNOPSYS
.nf
#include "logmmm.h"
void markAllBdd(value)
short value;
.fi
.SH PARAMETER
.TP 20
\fIvalue\fP
value to assign
.SH DESCRIPTION
\fBmarkAllBdd()\fP assigns to \fIvalue\fP the marks of all the nodes used in the BDDs system. 
.SH SEE ALSO
.BR log (1),
.BR bdd (1),
.BR markBdd (3),
.BR numberNodeBdd (3),
.BR numberNodeAllBdd (3),
.BR supportChain_listBdd (3).

.so man1/alc_bug_report.1

