.\"   $Id: markBdd.3,v 1.1.1.1 2002/04/03 13:13:26 ludo Exp $
.\" @(#)markBdd.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH MARKBDD 3 "October 1, 1997" "ASIM/LIP6" "BDD functions"
.so man1/alc_origin.1
.SH NAME
\fBmarkBdd\fP \- marks all nodes of a BDD 
.SH SYNOPSYS
.nf
#include "logmmm.h"
void markBdd(pBdd,value)
pNode pBdd;
short value;
.fi
.SH PARAMETERS
.TP 20
\fIpBdd\fP
BDD to mark 
.TP 20
\fIvalue\fP
value to assign
.SH DESCRIPTION
\fBmarkBdd()\fP assigns to \fIvalue\fP the field \fImark\fP of all the nodes used in \fIpBdd\fP. This function is used for the garbage collection. When a node is created, its mark is set to 0 (the default value).
.SH SEE ALSO
.BR log (1),
.BR bdd (1),
.BR markAllBdd (3),
.BR numberNodeBdd (3),
.BR numberNodeAllBdd (3),
.BR gcNodeBdd (3).

.so man1/alc_bug_report.1

