.\"   $Id: numberNodeAllBdd.3,v 1.1.1.1 2002/04/03 13:13:26 ludo Exp $
.\" @(#)numberNodeAllBdd.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH NUMBERNODEALLBDD 3 "October 1, 1997" "ASIM/LIP6" "BDD functions"
.so man1/alc_origin.1
.SH NAME
\fBnumberNodeAllBdd\fP \- count the number of nodes used in the BDD system
.SH SYNOPSYS
.nf
#include "logmmm.h"
int numberNodeAllBdd()
.fi
.SH DESCRIPTION
\fBnumberNodeAllBdd()\fP count the number of the nodes that are used in the BDD system 
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"
pNode nodeA,nodeB,nodeC;
pNode res;
chain_list *pt;

initializeBdd(SMALL_BDD);
nodeA = createNodeTermBdd(3);
nodeB = createNodeTermBdd(3);
nodeC = createNodeTermBdd(4);
pt = NULL;
pt = addListBdd(pt,nodeA);
pt = addListBdd(pt,nodeB);
pt = addListBdd(pt,nodeC);
res = applyBdd(OR,pt);
printf("number of nodes = %d",numberNodeAllBdd());

/* it will display 
number of nodes = 5
*/
	
destroyBdd(1);
.fi
.SH SEE ALSO
.BR log (1),
.BR bdd (1),
.BR addListBdd (3),
.BR numberNodeBdd (3),
.BR notBdd (3),
.BR constraintBdd (3),
.BR composeBdd (3),
.BR displayBdd (3),
.BR createNodeTermBdd (3).

.so man1/alc_bug_report.1

