.\"   $Id: resetBdd.3,v 1.1.1.1 2002/04/03 13:13:26 ludo Exp $
.\" @(#)resetBdd.2 7.01 92/08/22 ; Labo masi cao-vlsi; Author : Luc Burgun
.TH RESETBDD 3 "October 1, 1997" "ASIM/LIP6" "BDD functions"
.so man1/alc_origin.1
.SH NAME
\fBresetBdd\fP \- resets the BDDs system 
.SH SYNOPSYS
.nf
#include "logmmm.h"
void resetBdd()
.fi
.SH DESCRIPTION
\fBresetBdd()\fP resets the BDDs system. This function can be only called after the \fBinitializeBdd()\fP function.
.SH EXAMPLE
.nf
#include "mutnnn.h"		/* mbk utilities */
#include "logmmm.h"

initializeBdd(LARGE_BDD);

/* first application using BDD ... */

resetBdd();

/* second application using BDD ... */

destroyBdd(1);
.fi
.SH SEE ALSO
.BR log (1),
.BR bdd (1),
.BR destroyBdd (3),
.BR gcNodeBdd (3),
.BR markAllBdd (3),
.BR numberNodeAllBdd (3),
.BR resetBdd (3).

.so man1/alc_bug_report.1

