.\"   $Id: fsm.1,v 1.1 2002/03/20 14:26:43 ludo Exp $
.\" @(#)fsm.1 1.01 96/02/07 UPMC; Fsmhor : Jacomme Ludovic
.TH FSM101 1 "October 1, 1997" "ASIM/LIP6" "ALLIANCE FSM LIBRARY"
.SH NAME
fsm \- Finite State Machine representation. 
.so man1/alc_origin.1
.SH DESCRIPTION
\fBfsm\fP is a library that enables to represent finite state machine.

.TP
Types :
.TP 20
.br
\fBfsmin_list\fP
\- inputs of a FSM.
.TP
\fBfsmout_list\fP
\- outputs of a FSM.
.TP
\fBfsmport_list\fP
\- ports of a FSM.
.TP
\fBfsmlocout_list\fP
\- state output assign.
.TP
\fBfsmtrans_list\fP
\- transition of a FSM.
.TP
\fBfsmstate_list\fP
\- state of a FSM.
.TP
\fBfsmstack_list\fP
\- stack of a FSM.
.TP
\fBfsmfig_list\fP
\- FSM figure.

.TP
Functions :
.TP 20
.br

...

.TP 0
libFsm101.a :


.so man1/alc_bug_report.1

