.\"   $Id: addrdsfig.3,v 1.1.1.1 2002/03/13 13:37:37 fred Exp $
.\" @(#)addrdsfig.1 1.11 93/08/18 ; Labo masi cao-vlsi
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
addrdsfig
.XE
.XS0 \n%
.ti 0.2i
addrdsfig
.XE0 \}
.TH ADDRDSFIG 3 "October 1, 1997" "ASIM/LIP6" "RDS PHYSICAL FUNCTIONS"
.SH NAME
addrdsfig \- adds a figure
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include"rdsnnn.h"
rdsfig_list \(**addrdsfig( Name, Size )
  char        \(**Name;
  unsigned int Size;
.SH PARAMETER
.TP 20
\fIName\fP
Name of the figure to add to the figures's list.
.TP
\fISize\fP
Size of the user structure (if defined) added to the rdsrec_list structure.
.SH DESCRIPTION
The addrdsfig function adds a new figure called 'Name' to the head of figures's list and becomes itself the list head (HEAD_RDSFIG pointer). 
.br
The field \fINAME\fP of the figure is set to \'Name\'.
.br
The field \fISIZE\fP of the figure is set to \'Size\'.
.br
The field MODE of the figure is set to \'A\'.
.PP
\fINote\fI :
.PP
Name allocation is done with the namealloc() MBK function.
.PP
If user structure isn't defined, the user has to set parameter 'Size' to 0L. 
.SH RETURN VALUE
Pointer to the newly created figure.It's also the HEAD_RDSFIG pointer.
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"Rds202: rdsalloc error, can't continue !"
.ft R
.RS
it's impossible to allocate the memory size desired
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
        #include "mutnnn.h"
	#include "rdsnnn.h"
        #include "rtlnnn.h"
	 typedef struct UserStruct
	  {
	    char \(**STRING;
	    void \(**USER1;
	  } UserStruct;
	 main()
	  {
	    rdsfig_list \(**RdsFigure;
            mbkenv();
            rdsenv();
            loadrdsparam();
	    RdsFigure = \fBaddrdsfig\fP ("core",sizeof ( UserStruct ) );
	    printf("FIGURE NAME = %s\\n",RdsFigure->NAME);
	    /\(** The new figure is head of figure list \(**/
	    printf("HEAD_RDSFIG : FIGURE NAME = %s\\n",HEAD_RDSFIG->NAME);
	  }
.ft R
.fi
.SH SEE ALSO
.BR librds,
.BR delrdsfig,
.BR viewrdsfig


.so man1/alc_bug_report.1

