.\"   $Id: allocrdswin.3,v 1.1.1.1 2002/03/13 13:37:37 fred Exp $
.\" @(#)allocrdswin.1 1.11 93/08/18 ; Labo masi cao-vlsi
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
allocrdswin
.XE
.XS0 \n%
.ti 0.2i
allocrdswin
.XE0 \}
.TH ALLOCRDSWIN 3 "October 1, 1997" "ASIM/LIP6" "RDS PHYSICAL FUNCTIONS"
.SH NAME
allocrdswin \- allocates window's table
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "rwinnn.h"
 rdswin_list \(**allocrdswin( Number )
    unsigned int Number;
.ft R
.fi
.SH PARAMETER
.TP 20
\fINumber\fP
Number of windows contained in the window's table.
.SH DESCRIPTION
The \fIallocrdswin\fP allocates a window's table. The number of windows is specified by the parameter \'Number\' of the function. To determine the size of the parameter \'Number\', the user has to multiplicate width by height of his table in number of windows. Each item of the table is a pointer to a rdswin_list structure which contains rectangles sorted by layer (see librwi).
.SH RETURN VALUE
The pointer to the table is returned.
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"Rds202: rdsalloc error, can't continue !"
.ft R
.RS
it's impossible to allocate the memory size for the table
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
        #include "mutnnn.h"
        #include "rdsnnn.h"
        #include "rwinnn.h"
        #include "rtlnnn.h"
        main()
          {
            rdswindow \(**RdsWindow;
            RdsWindow = allocrdswindow();
            RdsWindow->XMIN = -200;
            RdsWindow->YMIN = -200;
            RdsWindow->XMAX =  200;
            RdsWindow->YMAX =  200;
            RdsWindow->DX   =  4;
            RdsWindow->DY   =  4;
            RdsWindow->SIDE =  100;
            RdsWindow->SIZE =  RdsWindow->DX \(** RdsWindow->DY ;
            RdsWindow->WINTAB = \fBallocrdswin\fP( RdsWindow->SIZE ); 
            . . .
          }
.ft R
.fi
.SH SEE ALSO
.BR librwi


.so man1/alc_bug_report.1

