.\"   $Id: allocrdswindow.3,v 1.1.1.1 2002/03/13 13:37:37 fred Exp $
.\" @(#)allocrdswindow.1 1.11 93/08/18 ; Labo masi cao-vlsi
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
allocrdswindow
.XE
.XS0 \n%
.ti 0.2i
allocrdswindow
.XE0 \}
.TH ALLOCRDSWINDOW 3 "October 1, 1997" "ASIM/LIP6" "RDS PHYSICAL FUNCTIONS"
.SH NAME
allocrdswindow \- allocates a window structure 
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "rwinnn.h"
 rdswindow \(**allocrdswindow()
.ft R
.fi
.SH PARAMETER
none
.SH DESCRIPTION
The \fIallocrdswindow\fP allocates a window structure (rdswindow) which is used to create an \'object\' window (see librwi). It contains fields information about the window's table and the pointer to the window's table. It's the head of windowing.
.SH RETURN VALUE
The pointer to the rdswindow structure allocated is returned.
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"Rds202: rdsalloc error, can't continue !"
.ft R
.RS
it's impossible to allocate the memory size desired.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
        #include "mutnnn.h"
        #include "rdsnnn.h"
        #include "rwinnn.h"
        #include "rtlnnn.h"
        main()
          {
            rdswindow \(**RdsWindow;
            RdsWindow = \fBallocrdswindow\fP();
            RdsWindow->XMIN = -200;
            RdsWindow->YMIN = -200;
            RdsWindow->XMAX =  200;
            RdsWindow->YMAX =  200;
            RdsWindow->DX   =  4;
            RdsWindow->DY   =  4;
            RdsWindow->SIDE =  100;
            RdsWindow->SIZE =  RdsWindow->DX \(** RdsWindow->DY ;
            RdsWindow->WINTAB = allocrdswin( RdsWindow->SIZE );
            . . .
          }
.ft R
.fi
.SH SEE ALSO
.BR librwi,
.BR buildrdswindow,
.BR destroyrdswindow,
.BR viewrdswindow


.so man1/alc_bug_report.1

