.\"   $Id: allocrdswinrec.3,v 1.1.1.1 2002/03/13 13:37:37 fred Exp $
.\" @(#)allocrdswinrec.1 1.11 93/08/18 ; Labo masi cao-vlsi
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
allocrdswinrec
.XE
.XS0 \n%
.ti 0.2i
allocrdswinrec
.XE0 \}
.TH ALLOCRDSWINREC 3 "October 1, 1997" "ASIM/LIP6" "RDS PHYSICAL FUNCTIONS"
.SH NAME
allocrdswinrec \- allocates a structure used to create a list of tables of rectangles.
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "rwinnn.h"
 rdswinrec_list \(**allocrdswinrec()
.ft R
.fi
.SH PARAMETER
none
.SH DESCRIPTION
The \fIallocrdswinrec\fP function allocates a data structure named "rdswinrec_list" used to contain rectangles. This structure contains a list of tables of rdsrec_list structures (see librwi and librds).
.SH RETURN VALUE
The pointer to the newly allocated structure is returned.
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"Rds202: rdsalloc error, can't continue !"
.ft R
.RS
it's impossible to allocate the memory size desired
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
        #include "mutnnn.h"
        #include "rdsnnn.h"
        #include "rwinnn.h"
        #include "rtlnnn.h"
        main()
          {
            rdsrec_list    \(**Rectangle;
            rdswinrec_list \(**WinRec, \(**HeadWinRec;
            mbkenv();
            rdsenv();
            loadrdsparam();
            WinRec = HeadWinRec = \fBallocrdswinrec\fP();
            /\(** Fill the table with rectangles \(**/
            for ( Counter = 0 ; Counter < RWI_MAX_REC ; Counter ++ )
             {
               if ( Rectangle == (rdsrec_list \(**) NULL ) break;
               WinRec->RECTAB[Counter] = Rectangle;
               Rectangle = Rectangle->NEXT;
             }
            if ( Counter == RWI_MAX_REC ) 
             {
               /\(** the table is full : allocation of a new table \(**/
               WinRec->NEXT = allocrdswinrec();
               WinRec = WinRec->NEXT;
             }
            . . . . 
          }
.ft R
.fi
.SH SEE ALSO
.BR librwi


.so man1/alc_bug_report.1

