.\"   $Id: allocrdsfig.3,v 1.1.1.1 2002/03/13 13:37:37 fred Exp $
.\" @(#)allocrdsfig.1 1.11 93/08/18 ; Labo masi cao-vlsi
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
allocrdsfig
.XE
.XS0 \n%
.ti 0.2i
allocrdsfig
.XE0 \}
.TH ALLOCRDSFIG 3 "October 1, 1997" "ASIM/LIP6" "RDS PHYSICAL FUNCTIONS"
.SH NAME
 allocrdsfig \- allocs memory for a figure
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "rdsnnn.h"
rdsfig_list \(**allocrdsfig()
.ft R
.fi
.SH PARAMETER
none
.SH DESCRIPTION
The \fIallocrdsfig\fP function allocates a memory block for rdsfig_list structure. Fields contained in the structure are set to NULL for pointers or 0L for numbers.
.TP
NOTE: Allocation by block ( see rdsalloc() function ).
.SH RETURN VALUE
\fBallocrdsfig\fP returns a pointer to the rdsfig_list structure allocated.
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"Rds202: rdsalloc error, can't continue !"
.ft R
.RS
it's impossible to allocate the memory size desired.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
         #include "mutnnn.h"
         #include "rdsnnn.h"
         #include "rtlnnn.h"
	    main()
	     {
	       rdsfig_list \(**RdsFigure;
               mbkenv();
               rdsenv();
               loadrdsparam();
	       RdsFigure = \fBallocrdsfig\fP ();
	       RdsFigure->NAME = namealloc ("core");
	       ...
	     }
.ft R
.fi
.SH SEE ALSO
.BR librds,
.BR rdsalloc,
.BR rdsfree,
.BR freerdsfig


.so man1/alc_bug_report.1

