.\"   $Id: conmbkrds.3,v 1.1.1.1 2002/03/13 13:37:37 fred Exp $
.\" @(#)conmbkrds.1 1.11 93/08/18 ; Labo masi cao-vlsi
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
conmbkrds
.XE
.XS0 \n%
.ti 0.2i
conmbkrds
.XE0 \}
.TH CONMBKRDS 3 "October 1, 1997" "ASIM/LIP6" "RDS PHYSICAL FUNCTIONS"
.SH NAME
 conmbkrds \- converts MBK connector to RDS rectangle
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
 #include "rfmnnn.h"
  rdsrec_list \(**conmbkrds( Figure, Connector )
    rdsfig_list \(**Figure;
    phcon_list  \(**Connector;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIFigure\fP
Rds Figure which has to receive the connector.
.TP
\fIConnector\fP
MBK connector to convert to RDS format.
.SH DESCRIPTION
The \fIconmbkrds\fP function creates a RDS rectangle (connector) with a connector from MBK structure \fIphcon_list\fP. The RDS rectangle is added to the figure defined in parameter of the function.
.SH RETURN VALUE
The pointer to the RDS rectangle created.
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"Rds202: rdsalloc error, can't continue !"
.ft R
.RS
it's impossible to allocate the memory size desired
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
        #include "mphnnn.h"
        #include "mutnnn.h"
        #include "rdsnnn.h"
        #include "rfmnnn.h"
        #include "rtlnnn.h"
        typedef struct UserStruct
         {
           char \(**STRING;
           void \(**USER1;
         } UserStruct;
        main()
          {
            phfig_list  \(**MbkFigure;
            rdsfig_list \(**RdsFigure;
            rdsrec_list \(**Con;
            mbkenv();
            rdsenv();
            loadrdsparam();
            RdsFigure = addrdsfig ("core",sizeof ( UserStruct ) );
            MbkFigure->PHCON =
                addphcon ( MbkFigure,NORTH, "in_1", 9, 15, ALU1, 2);
            Con = \fBconmbkrds\fI (RdsFigure, MbkFigure->PHCON);
            . . .
          }
.ft R
.fi
.SH SEE ALSO
.BR librfm,
.BR viewrfmcon,
.BR loadrdsparam


.so man1/alc_bug_report.1

