.\"   $Id: delrdsfigrec.3,v 1.1.1.1 2002/03/13 13:37:37 fred Exp $
.\" @(#)delrdsfigrec.1 1.11 93/08/18 ; Labo masi cao-vlsi
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
delrdsfigrec
.XE
.XS0 \n%
.ti 0.2i
delrdsfigrec
.XE0 \}
.TH DELRDSFIGREC 3 "October 1, 1997" "ASIM/LIP6" "RDS PHYSICAL FUNCTIONS"
.SH NAME
delrdsfigrec \- deletes a rectangle of a figure
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include"rdsnnn.h"
 int delrdsfigrec( Figure, Rectangle )
      rdsfig_list \(**Figure;
      rdsrec_list \(**Rectangle;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIFigure\fP
Figure which contains the rectangle to delete.
.TP
\fIRectangle\fP
The rectangle to delete
.SH DESCRIPTION
The \fIdelrdsfigrec\fP function deletes a rectangle object (which is composed of the rdsrec_list structure and an eventually added structure) from a figure.
.SH RETURN VALUE
1 => The rectangle has been deleted.
.br
0 => The rectangle doesn't exist.
.SH ERRORS
None
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
        #include "mutnnn.h"
        #include "rdsnnn.h"
        #include "rtlnnn.h"
        typedef struct UserStruct
         {
           char \(**STRING;
           void \(**USER1;
         } UserStruct;
         main()
          {
            rdsfig_list \(**Figure;
            rdsrec_list \(**Rectangle;
            int          Result;
            mbkenv();
            rdsenv();
            loadrdsparam();
            Figure = addrdsfig ("core",sizeof ( UserStruct ) );
            Rectangle =
             addrdsfigrec(Figure,"Alu1",RDS_ALU1,2,4,12,1);
            /\(**
              deletes the rectangle of the figure
            \(**/
            Result = \fBdelrdsfigrec\fP ( Figure,Rectangle );
            if ( Result == 0 ) printf("Rectangle not found !\\n");
          }
.ft R
.fi
.SH SEE ALSO
.BR librds,
.BR allocrdsfigrec


.so man1/alc_bug_report.1

