.\"   $Id: refmbkrds.3,v 1.1.1.1 2002/03/13 13:37:37 fred Exp $
.\" @(#)refmbkrds.1 1.11 93/08/18 ; Labo masi cao-vlsi
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
refmbkrds
.XE
.XS0 \n%
.ti 0.2i
refmbkrds
.XE0 \}
.TH REFMBKRDS 3 "October 1, 1997" "ASIM/LIP6" "RDS PHYSICAL FUNCTIONS"
.SH NAME
refmbkrds \- adds to RDS figure a references from a MBK figure
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "rfmnnn.h"
 rdsrec_list \(**refmbkrds( Figure, Reference )
   rdsfig_list \(**Figure;
   phref_list  \(**Reference;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIFigure\fP
The RDS figure which has to receive the reference to convert.
.TP
\fIReference\fP
MBK reference to convert to RDS rectangle.
.SH DESCRIPTION
The \fIrefmbkrds\fP function creates a RDS reference with a MBK reference. The reference is attached to the RDS figure in parameter of the refmbkrds function.
.SH RETURN VALUE
Pointer to the newly created RDS reference.
.SH ERRORS
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
"Rds202: rdsalloc error, can't continue !"
.ft R
.RS
it's impossible to allocate the memory size desired
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
        #include "mphnnn.h"
        #include "mutnnn.h"
        #include "rdsnnn.h"
        #include "rfmnnn.h"
        #include "rtlnnn.h"
        typedef struct UserStruct
         {
           char \(**STRING;
           void \(**USER1;
         } UserStruct;
        main()
          {
            phfig_list  \(**MbkFigure;
            rdsfig_list \(**RdsFigure;
            rdsrec_list \(**Ref;
            mbkenv();
            rdsenv();
            loadrdsparam();
            RdsFigure = addrdsfig ("core",sizeof ( UserStruct ) );
            MbkFigure->PHREF = addphref ( MbkFigure,"ref_con", "ref_1", 9, 15);
            Ref = \fBrefmbkrds\fP (RdsFigure, MbkFigure->PHREF);
            viewrdsrec ( Ref );
          }
.ft R
.fi
.SH SEE ALSO
.BR librfm,
.BR viewrfmref,
.BR loadrdsparam


.so man1/alc_bug_report.1

