.\"   $Id: roundrdsrec.3,v 1.1.1.1 2002/03/13 13:37:37 fred Exp $
.\" @(#)roundrdsrec.1 1.11 93/08/18 ; Labo masi cao-vlsi
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
roundrdsrec
.XE
.XS0 \n%
.ti 0.2i
roundrdsrec
.XE0 \}
.TH ROUNDRDSREC 3 "October 1, 1997" "ASIM/LIP6" "RDS PHYSICAL FUNCTIONS"
.SH NAME
roundrdsrec \- adjusts a rectangle to lambda grid step
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "rfmnnn.h"
 void roundrdsrec( Rectangle )
    rdsrec_list \(**Rectangle;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIRectangle\fP
RDS rectangle to treat.
.SH DESCRIPTION
the \fIroundrdsrec\fP function adjusts (in lambda) to lower grid step for rectangle extremity which has coordinates (X,Y), adjusts to upper grid step for rectangle extremity which has coordinates (X+DX,Y+DY).
.SH RETURN VALUE
nothing
.SH ERRORS
none
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
        #include "mphnnn.h"
        #include "mutnnn.h"
        #include "rdsnnn.h"
        #include "rfmnnn.h"
        #include "rtlnnn.h"
        typedef struct UserStruct
         {
           char \(**STRING;
           void \(**USER1;
         } UserStruct;
        main()
          {
            rdsfig_list \(**RdsFigure;  
            rdsrec_list \(**Rectangle;
            mbkenv();
            rdsenv();
            loadrdsparam();
            RdsFigure        = addrdsfig("core_2",sizeof(UserStruct));
            Rectangle   =
               addrdsfigrec(RdsFigure, "seg", RDS_ALU1, 2.5, 3.5, 6, 7);
            viewrfmrec ( Rectangle );            
            /\(** \(**/ \fBroundrdsrec\fP ( Rectangle );
            /\(** view rectangle after rounding \(**/
            viewrfmrec ( Rectangle );
          }
.ft R
.fi
.SH SEE ALSO
.BR librfm,
.BR viewrfmrec
.BR et_un_autre_see_also


.so man1/alc_bug_report.1

