.\"   $Id: viewrfmcon.3,v 1.1.1.1 2002/03/13 13:37:38 fred Exp $
.\" @(#)viewrfmcon.1 1.11 93/08/18 ; Labo masi cao-vlsi
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
viewrfmcon
.XE
.XS0 \n%
.ti 0.2i
viewrfmcon
.XE0 \}
.TH VIEWRFMCON 3 "October 1, 1997" "ASIM/LIP6" "RDS PHYSICAL FUNCTIONS"
.SH NAME
viewrfmcon \- displays connector caracteristics in MBK and RDS format.
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "rfmnnn.h"
 void viewrfmcon( Connector, Rectangle )
    phcon_list  \(**Connector;
    rdsrec_list \(**Rectangle;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIConnector\fP
MBK Connector to visualizate
.TP
\fIRectangle\fP
RDS Connector to visualizate
.SH DESCRIPTION
The \fIviewrfmcon\fP function displays caracteristics of a connector in MBK and RDS format.
.SH RETURN VALUE
nothing
.SH ERRORS
none
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
        #include "mphnnn.h"
        #include "mutnnn.h"
        #include "rdsnnn.h"
        #include "rfmnnn.h"
        #include "rtlnnn.h"
        typedef struct UserStruct
         {
           char \(**STRING;
           void \(**USER1;
         } UserStruct;
        main()
          {
            phfig_list  \(**MbkFigure;
            rdsfig_list \(**RdsFigure;
            rdsrec_list \(**RdsConnector;
            mbkenv();
            rdsenv();
            loadrdsparam();
            RdsFigure =
               addrdsfig ("core",sizeof ( UserStruct ) );
            MbkFigure->PHCON =
               addphcon ( MbkFigure, NORTH, "c_1", 14, 5, ALU1, 2);
            RdsConnector = conmbkrds(RdsFigure, MbkFigure->PHCON);
            /\(** \(**/ \fBviewrfmcon\fP ( MbkFigure->PHCON, RdsConnector );            
          }
.ft R
.fi
.SH SEE ALSO
.BR librfm,
.BR conmbkrds,
.BR insconmbkrds


.so man1/alc_bug_report.1

