.\"   $Id: viewrfmvia.3,v 1.1.1.1 2002/03/13 13:37:38 fred Exp $
.\" @(#)viewrfmvia.1 1.11 93/08/18 ; Labo masi cao-vlsi
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
viewrfmvia
.XE
.XS0 \n%
.ti 0.2i
viewrfmvia
.XE0 \}
.TH VIEWRFMVIA 3 "October 1, 1997" "ASIM/LIP6" "RDS PHYSICAL FUNCTIONS"
.SH NAME
viewrfmvia \- displays contact caracteristics in MBK and RDS format.
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "rfmnnn.h"
void viewrfmvia( Via, Rectangle )
   phvia_list  \(**Via;
   rdsrec_list \(**Rectangle;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIVia\fP
MBK contact to visualizate.
.TP
\fIRectangle\fP
RDS contact Rds to visualizate.
.SH DESCRIPTION
The \fIviewrfmvia\fP function displays caracteristics of a contact in MBK and RDS format.
.SH RETURN VALUE
nothing
.SH ERRORS
none
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
        #include "mphnnn.h"
        #include "mutnnn.h"
        #include "rdsnnn.h"
        #include "rfmnnn.h"
        #include "rtlnnn.h"
        typedef struct UserStruct
         {
           char \(**STRING;
           void \(**USER1;
         } UserStruct;
        main()
          {
            phfig_list  \(**MbkFigure;
            rdsfig_list \(**RdsFigure;
            rdsrec_list \(**RdsVia;
            mbkenv();
            rdsenv();
            loadrdsparam();
            RdsFigure = addrdsfig ("core",sizeof ( UserStruct ) );
            MbkFigure->PHVIA = addphvia ( MbkFigure, CONT_VIA, 3, 7);
            RdsVia = viambkrds(RdsFigure, MbkFigure->PHVIA);
            /\(** \(**/ \fBviewrfmvia\fP ( MbkFigure->PHVIA, RdsVia );            
          }
.ft R
.fi
.SH SEE ALSO
.BR librfm,
.BR viambkrds,
.BR insviambkrds


.so man1/alc_bug_report.1

