.\"   $Id: viewrdsfig.3,v 1.1.1.1 2002/03/13 13:37:37 fred Exp $
.\" @(#)viewrdsfig.1 1.11 93/08/18 ; Labo masi cao-vlsi
.if t \{\
.so man1/alc_contents.mac
.XS \n%
.ti 0.2i
viewrdsfig
.XE
.XS0 \n%
.ti 0.2i
viewrdsfig
.XE0 \}
.TH VIEWRDSFIG 3 "October 1, 1997" "ASIM/LIP6" "RDS PHYSICAL FUNCTIONS"
.SH NAME
 viewrdsfig \- view caracteristics of a figure
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
 #include "rdsnnn.h"
  void viewrdsfig( Figure )
   rdsins_list \(**Figure;
.ft R
.fi
.SH PARAMETER
.TP 20
\fIFigure\fP
Pointer to the figure to visualize.
.SH DESCRIPTION
The \fIviewrdsfig\fP function displays caracteristics of the figure called \'Figure\' and all the objets contained in this figure.
.TP
figure's parameters displayed to screen :
.RS
.TP 
\fINAME\fP
figure's name.
.TP 
\fIMODE\fP
loading mode of the figure.
.TP 
\fISIZE\fP
size of user structure added to the rdsrec_list structure.
.RE
Displays also rectangle and instance parameters of the figure (see viewrdsins and viewrdsrec functions).
.SH RETURN VALUE
nothing
.SH ERRORS
none
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
        #include "mutnnn.h"
        #include "rdsnnn.h"
        #include "rtlnnn.h"
        typedef struct UserStruct
         {
           char \(**STRING;
           void \(**USER1;
         } UserStruct;
         main()
          {
            rdsfig_list \(**Figure;
            rdsrec_list \(**Rectangle;
            rdsins_list \(**Instance;
            mbkenv();
            rdsenv();
            loadrdsparam();
            Figure = addrdsfig ("core",sizeof ( UserStruct ) );
            Instance  = addrdsins (Figure,"na2_y","and2",RDS_NOSYM,8,6);
            Rectangle =
             addrdsfigrec(Figure,"Alu1",RDS_ALU1,2,4,12,1);
            /\(**
              visualization of the figure and its items
            \(**/
            /\(** \(**/ \fBviewrdsfig\fP ( Figure );
          }
.ft R
.fi
.SH SEE ALSO
.BR librds,
.BR viewrdsrec,
.BR viewrdsins


.so man1/alc_bug_report.1

