.\"   $Id: autfreeblock.3,v 1.1 2002/03/21 13:17:24 ludo Exp $
.\" @(#)autfreeblock.2 2.7 96/07/02 ; Labo masi cao-vlsi; Author : Jacomme Ludovic
.TH AUTFREEBLOCK 3 "October 1, 1997" "ASIM/LIP6" "AUT FUNCTIONS"
.SH NAME
autfreeblock \- releases a memory block
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "aut101.h"
void autfreeblock( Pointer )
   char \(** Pointer;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIPointer\fP
Pointer to be given back to the system
.SH DESCRIPTION
\fBautfreeblock\fP frees a pointer. It is now a day just
an encapsulation of the system free function, but may evolve to a
special allocator in the future. Its use is strongly encouraged.
.br
.SH RETURN VALUE
\fBautfreeblock\fP returns nothing.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "aut101.h"
  char \(**Pointer;
  Pointer = autallocblock( 1024 );
  ...
  autfreeblock( Pointer );
.ft R
.fi
.SH SEE ALSO
.BR aut (1),
.BR autresizeblock(3),
.BR autallocheap(3),
.BR autallocblock(3),
.BR autfreeheap(3).


.so man1/alc_bug_report.1

