.\"   $Id: auth2elem.3,v 1.1 2002/03/21 13:17:24 ludo Exp $
.\" @(#)auth2elem.2 1.01 96/02/07 UPMC; Author: Jacomme Ludovic
.TH AUTH2ELEM 3 "October 1, 1997" "ASIM/LIP6" "AUT STRUCTURE DEFINITIONS"
.SH NAME
auth2elem \- element in an hash table with two keys.
.SH DESCRIPTION
The \fBauth2elem\fP structure is used to describe an hash element.
.LP
The declarations needed to work on \fBauth2elem\fP are available in the header file
\fI"/labo/include/aut101.h"\fP, where '\fI101\fP' is the actual aut version.
.LP
The following C structure supports the description of an hash element :
.RS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
.ta 3n 20n 30n
  typedef struct auth2elem
  {
    char \(**KEY1;
    char \(**KEY2;
    long  VALUE;
  } auth2elem;
.ft R
.fi
.RE
.TP 20
\fIKEY1\fP
 KEY1 is the first hash element key, for example a name created with \fInamealloc\fP.
.TP
\fIKEY2\fP
 KEY2 is the second hash element key, for example a name created with \fInamealloc\fP.
.TP
\fIVALUE\fP
 VALUE is the value associated to the two keys \fIKEY1\fP and \fIKEY2\fP. 
.SH SEE ALSO
.BR aut (1),
.BR auth2table(3),


.so man1/alc_bug_report.1

