.\"   $Id: auth2table.3,v 1.1 2002/03/21 13:17:24 ludo Exp $
.\" @(#)auth2table.2 1.01 96/02/07 UPMC; Author: Jacomme Ludovic
.TH AUTH2TABLE 3 "October 1, 1997" "ASIM/LIP6" "AUT STRUCTURE DEFINITIONS"
.SH NAME
auth2table \- hash table structure
.SH DESCRIPTION
The \fBauth2table\fP structure is used to describe an hash table with two keys.
.LP
The declarations needed to work on \fBauth2table\fP are available in the header file
\fI"/labo/include/aut101.h"\fP, where '\fI101\fP' is the actual aut version.
.LP
The following C structure supports the description of an hash element :
.RS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
.ta 3n 20n 30n
  typedef struct auth2table
  {
    auth2elem \(**TABLE;
    long      TABLE_SIZE;
    long      NUMBER_ELEM;
    long      NUMBER_ADD;
    long      NUMBER_SCAN;
    long      NUMBER_DEL;
    long      NUMBER_STRETCH;
  } auth2table;
.ft R
.fi
.RE
.TP 20
\fITABLE\fP
 TABLE is the hash element array.
.TP
\fITABLE_SIZE\fP
 TABLE_SIZE is the size of the hash table.
.TP
\fINUMBER_ELEM\fP
 NUMBER_ELEM is the number of element in the hash table.
.TP
\fINUMBER_ADD\fP
 NUMBER_ADD is the number of added elements.
.TP
\fINUMBER_SCAN\fP
 NUMBER_SCAN is the number of scans to find an element.
.TP
\fINUMBER_DEL\fP
 NUMBER_DEL is the number of deleted elements.
.TP
\fINUMBER_STRETCH\fP
 NUMBER_STRETCH is the number of hash table stretch.
.SH SEE ALSO
.BR aut (1),
.BR auth2table(3),


.so man1/alc_bug_report.1

