.\"   $Id: delablexprnum.3,v 1.1.1.1 2002/03/18 11:06:16 ludo Exp $
.\" @(#)delablexprnum.2 2.7 96/07/02 ; Labo masi cao-vlsi; Author : Jacomme Ludovic
.TH DELABLEXPRNUM 3 "October 1, 1997" "ASIM/LIP6" "ABL FUNCTIONS"
.SH NAME
delablexprnum \- deletes an operand in an expression.
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "abl101.h"
void delablexprnum( Expr, Number )
  chain_list \(**Expr;
  int         Number;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIExpr\fP
Expression where to delete an operand.
.TP
\fIsecond_param\fP
Operand number.
.SH DESCRIPTION
\fBdelablexprnum\fP deletes the operand \fINumber\fP + 1 in \fIExpr\fP.
.br
.SH RETURN VALUE
\fBdelablexprnum\fP returns nothing.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "abl101.h"
   chain_list \(**ExprA;
   chain_list \(**ExprB;
   chain_list \(**ExprC;
   chain_list \(**ExprAorBorC;
   ExprA = createablatom( "a" );
   ExprB = createablatom( "b" );
   ExprC = createablatom( "c" );
   ExprAorBorC = createablbinexpr( ABL_OR, ExprA, ExprB );
   ExprAorBorC = createablbinexpr( ABL_OR, ExprAorBorC, ExprC );
   ...
   delablexprnum( ExprAorBorC, 2 );
   /* displays (a or b) */
   viewablexpr( ExprAorBorC, ABL_VIEW_VHDL );
.ft R
.fi
.SH SEE ALSO
.BR abl (1),
.BR freeablexpr(3),
.BR delablexpr(3).


.so man1/alc_bug_report.1

