.\"   $Id: freeablexpr.3,v 1.1.1.1 2002/03/18 11:06:16 ludo Exp $
.\" @(#)freeablexpr.2 2.7 96/07/02 ; Labo masi cao-vlsi; Author : Jacomme Ludovic
.TH FREEABLEXPR 3 "October 1, 1997" "ASIM/LIP6" "ABL FUNCTIONS"
.SH NAME
freeablexpr \- frees an expression. 
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "abl101.h"
  void freeablexpr( Expr )
   chain_list \(**Expr;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIExpr\fP
Expression to free.
.SH DESCRIPTION
\fBfreeablexpr\fP frees the expression \fIExpr\fP even if
this expression is not a valid one.
.br
.SH RETURN VALUE
\fBfreeablexpr\fP returns nothing.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "abl101.h"
   chain_list \(**ExprA;
   chain_list \(**ExprB;
   chain_list \(**ExprAorB;
   ExprA = createablatom( "a" );
   ExprB = createablatom( "b" );
   ExprAorB  = createablbinexpr( ABL_OR, ExprA, ExprB );
   ...
   freeablexpr( ExprAorB );
   ExprAorB = (chain_list \(**)0;
   ...
.ft R
.fi
.SH SEE ALSO
.BR abl (1)
.BR delablexpr(3).


.so man1/alc_bug_report.1

