.\"   $Id: getablexprdepth.3,v 1.1.1.1 2002/03/18 11:06:16 ludo Exp $
.\" @(#)getablexprdepth.2 2.7 96/07/02 ; Labo masi cao-vlsi; Author : Jacomme Ludovic
.TH GETABLEXPRDEPTH 3 "October 1, 1997" "ASIM/LIP6" "ABL FUNCTIONS"
.SH NAME
getablexprdepth \- gives the depth of an expression.
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "abl101.h"
long getablexprdepth( Expr )
  chain_list \(**Expr;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIExpr\fP
Expression.
.SH DESCRIPTION
\fBgetablexprdepth\fP gives the depth of an expression.
.br
.SH RETURN VALUE
\fBgetablexprdepth\fP returns the depth of \fIExpr\fP.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "abl101.h"
   chain_list \(**ExprA;
   chain_list \(**ExprB;
   chain_list \(**ExprAorB;
   ExprA = createablatom( "a" );
   ExprB = createablatom( "b" );
   ExprAorB  = createablbinexpr( ABL_OR, ExprA, ExprB );
   /* displays 1 */
   printf( "%d", getablexprdepth( ExprAorB ) );
.ft R
.fi
.SH SEE ALSO
.BR abl (1)


.so man1/alc_bug_report.1

