.\"   $Id: isabloperinexpr.3,v 1.1.1.1 2002/03/18 11:06:16 ludo Exp $
.\" @(#)isabloperinexpr.2 2.7 96/07/02 ; Labo masi cao-vlsi; Author : Jacomme Ludovic
.TH ISABLOPERINEXPR 3 "October 1, 1997" "ASIM/LIP6" "ABL FUNCTIONS"
.SH NAME
isabloperinexpr \- tests if an operator appears in an expression.
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "abl101.h"
int isabloperinexpr( Expr, Oper )
  chain_list \(**Expr;
  long        Oper;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIExpr\fP
Expression where to search.
.TP
\fIOper\fP
Operator to search.
.SH DESCRIPTION
\fBisabloperinexpr\fP tests if \fIOper\fP appears in \fIExpr\fP.
.br
.SH RETURN VALUE
\fBisabloperinexpr\fP returns 1 if \fIOper\fP appears in \fIExpr\fP
and 0 otherwise.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "abl101.h"
  chain_list \(**Expr;
   Expr = createablbinexpr( ABL_AND, 
                            createablatom( "a" ),
                            createablatom( "b" ) );
   /* displays   1 */
   printf( "%d", isabloperinexpr( Expr, ABL_AND ) );
.ft R
.fi
.SH SEE ALSO
.BR abl (1)


.so man1/alc_bug_report.1

