.\"   $Id: viewablexprstr.3,v 1.1.1.1 2002/03/18 11:06:16 ludo Exp $
.\" @(#)viewablexprstr.2 2.7 96/07/02 ; Labo masi cao-vlsi; Author : Jacomme Ludovic
.TH VIEWABLEXPRSTR 3 "October 1, 1997" "ASIM/LIP6" "ABL FUNCTIONS"
.SH NAME
viewablexprstr \- displays an expression in a str.
.so man1/alc_origin.1
.SH SYNOPSYS
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "abl101.h"
char *viewablexprstr( Expr, Mode )
  chain_list \(**Expr;
  int         Mode;
.ft R
.fi
.SH PARAMETERS
.TP 20
\fIExpr\fP
Expression to display.
.TP
\fIMode\fP
The notation type.
.SH DESCRIPTION
\fBviewablexprstr\fP displays \fIExpr\fP in a string, with the notation 
specified by \fIMode\fP.  The following notation types are available 
ABL_VIEW_INFIX, ABL_VIEW_PREFIX, ABL_VIEW_POSTFIX or ABL_VIEW_VHDL.
.br
.SH RETURN VALUE
\fBviewablexprstr\fP returns a pointer to the string where the expression
has been displayed in. This string MUSTN'T be freed.
.SH EXAMPLE
.ta 3n 6n 9n 12n 15n 18n 21n
.nf
.if n \{\
.ft B \}
.if t \{\
.ft CR \}
#include "abl101.h"
  chain_list \(**Expr;
  char       \(**String;
  Expr = createabloper( ABL_OR );
  addablhexpr( Expr, createablatom( "a" ) );
  addablhexpr( Expr, createablatom( "b" ) );
  /* displays (a or b) */
  String = viewablexprstr( Expr, ABL_VIEW_VHDL );
  printf( String );
.ft R
.fi
.SH SEE ALSO
.BR abl (1),
.BR viewablexprfile(3),
.BR viewablexpr(3).


.so man1/alc_bug_report.1

