.\"   $Id: beh_message.3,v 1.1.1.1 2002/04/04 14:54:48 ludo Exp $
.\" @(#)beh_message.2 108 Feb 15 1995 UPMC ; Pirouz BAZARGAN SABET
.TH BEH_MESSAGE 3 "October 1, 1997" "ASIM/LIP6" "BEH functions"

.so man1/alc_origin.1
.SH NAME
.PP
\fBbeh_message\fP

.SH SYNOPSYS
.PP
.nf
void beh_message (code, str)
int code;
char *str;
.fi

.SH PARAMETERS
.PP
.TP 10
\fIcode\fP
error\'s code
.TP 10
\fIstr\fP
a string to be printed within the error message

.SH DESCRIPTION
.PP
\fBbeh_message()\fP prints an error message on the standard output depending
on a message code. The \fIcode\fP parameter determines the message to be
printed.

.SH SEE ALSO
.PP
beh (3), beh_error(3)


.so man1/alc_bug_report.1

