.TH PAT2SPI 1 "May 23, 2004" "ASIM/LIP6" "CAO\-VLSI Reference Manual"
.SH NAME
.PP
\fIpat2spi\fP, PAT ALLIANCE format translator to Spice PWL format

.so man1/alc_origin.1
.SH SYNOPSIS
.PP
\fBpat2spi\fP 
[
.I -slope natural_value
]
.I In_filename
.I Out_filename

.SH DESCRIPTION
.PP
\fBpat2spi\fP is a translator from ALLIANCE pattern format (\fI".pat"\fP)
to spice PWL format (\fI".spi"\fP). An optional slope parameter can be used to specify
the slope value in pico second.

.SH EXAMPLE
.br
Converts adder4.pat using PWL commands and generates the file spice_pattern.spi
(that could be used in a SPICE testbench for example).

.PP
.ti 7
pat2spi -slope 100 adder4 spice_pattern

.SH SEE ALSO
.PP
asimut(1), pat(5)


.so man1/alc_bug_report.1

