.\" $Id: flatph.1,v 1.1 2002/04/29 14:15:50 czo Exp $
.TH FLATPH 1 "October 1, 1997" "ASIM/LIP6" "ALLIANCE USER COMMANDS"

.SH NAME
\fBflatph\fP \- FLATen PHysical figure

.so man1/alc_origin.1


.SH SYNOPSIS
.TP
\f4flatph\fR \fIphysical_figure instance output_name\fR

.SH DESCRIPTION
\f4flatph\fR FLATen PHysical figure

.SH SEE ALSO
.PP
.BR mbk(1)

.so man1/alc_bug_report.1

