.TH FSP 1 "October 1, 1997" "ASIM/LIP6" "CAO\-VLSI Reference Manual"
.SH NAME
.TP
fsp    
\- Formal proof between two FSM descriptions
.so man1/alc_origin.1
.SH SYNOPSIS
.TP
\fBfsp\fP [\fI-V\fP] \fIformat1\fP \fIformat2\fP \fIfile1\fP  \fIfile2\fP
.br
.SH DESCRIPTION
.br
Made to run on FSM descriptions, \fBfsp\fP supports the same subset of VHDL as syf 
(for further informations about this subset see SYF(1) and FSM(5)).
\fBfsp\fP uses a Reduced Ordered Binary Decision Diagrams representation and 
computes the product of the two FSM descriptions.
After this step, it explores the resulting FSM product and proves formally the equivalence
between the two initial FSM descriptions. 
Those two descriptions must have the same interface (VHDL entity).

.SH ENVIRONMENT VARIABLES
.br
.HP
.ti 7
\fIMBK_WORK_LIB\fP gives the path for the FSM descriptions.
The default value is the current directory.
.br
.HP
.ti 7
\fIMBK_CATA_LIB\fP gives some auxiliary pathes for the FSM descriptions.
The default value is the current directory.
.SH OPTIONS
.ti 7
\-V
Sets verbose mode on. Each step of the formal proof is displayed on the
standard output.
.br
.SH EXAMPLE
.br
	fsp fsm fsm digi digi2

.SH SEE ALSO
.br
 \fBsyf\fP (1), \fBfmi\fP (1), \fBfsm\fP (5), \fBxfsm\fP (1).

.so man1/alc_bug_report.1

